#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (  # noqa: E402
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_remainder01_report.json"


COMMON_OIL_INGREDIENTS = "Parfum (Fragrance), carrier oils, fixatives, and stabilizers."
COMMON_SPRAY_INGREDIENTS = "Alcohol Denat., Parfum (Fragrance), Aqua (Water), fragrance compounds, fixatives, and stabilizers."


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=8,
        barcode="6291110112422",
        brand="Al Rehab",
        name="Al Rehab Diwan Perfume Oil Roll-On 6ml (0.2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A rich unisex perfume oil with a spicy saffron-pepper opening, smooth oud-sandalwood heart, and warm ambergris-vanilla musk base.",
        top_notes="Saffron, Black Pepper",
        mid_notes="Agarwood, Sandalwood",
        base_notes="Ambergris, Vanilla, Musk",
        scent="Oriental woody warm spicy",
        feature="perfume oil roll-on; unisex; 6ml / 0.2 oz",
        keywords="Al Rehab, Diwan, Perfume Oil, Roll-On, Unisex, 6ml, 0.2 oz, Saffron, Oud, Vanilla",
        highlights=[
            "Concentrated perfume oil roll-on format.",
            "Unisex fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Warm oriental-woody style with saffron, oud, and vanilla.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product plus the exact size in the product name. This pass standardizes the title, gender, size fields, and SDS without inventing a new source story.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=31,
        barcode="6291110115782",
        brand="Al Rehab",
        name="Al Rehab Marine Spirit Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A fresh unisex eau de parfum with marine citrus sparkle up top, airy floral-aquatic heart notes, and a clean musky ambergris base.",
        top_notes="Bergamot, Mint, Sea Water",
        mid_notes="Calone, Lily, Jasmine",
        base_notes="Cedar, Musk, Ambergris",
        scent="Aquatic fresh aromatic musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Al Rehab, Marine Spirit, Eau De Parfum, Unisex, 100ml, 3.4 oz, Bergamot, Mint, Marine, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "100 mL / 3.4 oz bottle size.",
            "Clean aquatic-citrus profile for everyday wear.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product plus the exact 100ml naming. This pass standardizes the missing size fields and SDS rather than inventing fresh fragrance metadata.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=20,
        barcode="6291110104090",
        brand="Al Rehab",
        name="Al Rehab Pink Breeze Eau de Parfum Spray 50ml (1.65 oz) Women Perfume",
        gender="Women",
        size_oz=1.65,
        size_ml=50,
        volume_oz=1.65,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A playful women's eau de parfum with sweet berry fruits on top, creamy floral-gourmand notes through the heart, and honeyed vanilla musk in the base.",
        top_notes="Strawberry, Raspberry, Cherry",
        mid_notes="Custard, Tuberose, Freesia, Magnolia, Coconut",
        base_notes="Honey, Musk, Vanilla",
        scent="Fruity gourmand floral sweet",
        feature="eau de parfum spray; women; 50ml / 1.65 oz",
        keywords="Al Rehab, Pink Breeze, Eau De Parfum, Women, 50ml, 1.65 oz, Strawberry, Custard, Vanilla, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Al Rehab.",
            "50 mL / 1.65 oz bottle size.",
            "Sweet fruity-floral profile with creamy gourmand warmth.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already stored on the product plus the exact 50ml / 1.65 oz naming in the title. This pass fills the missing structured fields and SDS.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=5,
        barcode="6281110022913",
        brand="Al Rehab",
        name="Al Rehab Sara Eau de Parfum Spray 50ml (1.69 oz) Women Perfume",
        gender="Women",
        size_oz=1.69,
        size_ml=50,
        volume_oz=1.69,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A feminine eau de parfum with bergamot and almond up top, a soft peony-ylang floral heart, and comforting tonka-vanilla depth in the base.",
        top_notes="Bergamot, Bitter Almond",
        mid_notes="Peony, Ylang-Ylang",
        base_notes="Tonka Bean, Vanilla",
        scent="Floral citrus powdery sweet",
        feature="eau de parfum spray; women; 50ml / 1.69 oz",
        keywords="Al Rehab, Sara, Eau De Parfum, Women, 50ml, 1.69 oz, Bergamot, Almond, Peony, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Al Rehab.",
            "50 mL / 1.69 oz bottle size.",
            "Soft floral-almond profile with warm vanilla finish.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product and the exact size printed in the legacy name. This pass standardizes the title, gender, size fields, and SDS attachment.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=11,
        barcode="6291110111890",
        brand="Al Rehab",
        name="Al Rehab Spanish Vanilla Perfume Oil Roll-On 6ml (0.2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A comforting unisex perfume oil with creamy lactonic milk notes, a pure vanilla center, and a soft sugary musk base.",
        top_notes="Milk, Lactonic Cream",
        mid_notes="Vanilla",
        base_notes="Sugar, Soft Musk",
        scent="Vanilla lactonic sweet musky",
        feature="perfume oil roll-on; unisex; 6ml / 0.2 oz",
        keywords="Al Rehab, Spanish Vanilla, Perfume Oil, Roll-On, Unisex, 6ml, 0.2 oz, Vanilla, Milk, Musk",
        highlights=[
            "Concentrated perfume oil roll-on format.",
            "Unisex fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Creamy vanilla skin-scent style for solo wear or layering.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product plus the exact 6ml / 0.2 oz naming in the legacy title. This pass fills the missing structured size and SDS fields only.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=26,
        barcode="6281110003226",
        brand="Al Rehab",
        name="Al Rehab Allure of Oud Eau de Parfum Spray 35ml (1.15 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=1.15,
        size_ml=35,
        volume_oz=1.15,
        volume_ml=35,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A bold unisex eau de parfum with saffroned spice up top, a dry woody-resinous heart, and a leathery patchouli-cypriol base.",
        top_notes="Bergamot, Nutmeg, Black Pepper, Saffron",
        mid_notes="Iris, Cedarwood, Labdanum",
        base_notes="Leather, Sandalwood, Patchouli, Cypriol",
        scent="Woody leathery spicy smoky",
        feature="eau de parfum spray; unisex; 35ml / 1.15 oz",
        keywords="Al Rehab, Allure of Oud, Eau De Parfum, Unisex, 35ml, 1.15 oz, Saffron, Leather, Patchouli, Cypriol",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "35 mL / 1.15 oz bottle size.",
            "Dry spicy-oud style with leathery woody depth.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product and the exact 35ml / 1.15 oz size printed in the legacy title. This is a completion pass, not a guessed rewrite.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=13,
        barcode="6291110116116",
        brand="Al Rehab",
        name="Al Rehab Diala Perfume Oil Roll-On 6ml (0.2 oz) Women Perfume",
        gender="Women",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A soft women's perfume oil with heliotrope, mandarin, and orchid up top, creamy tropical fruit florals in the heart, and warm vanilla-musk sandalwood below.",
        top_notes="Heliotrope, Mandarin, Orchid",
        mid_notes="Peach, Mango, Coconut",
        base_notes="Vanilla, Musk, Sandalwood",
        scent="Creamy fruity floral sweet",
        feature="perfume oil roll-on; women; 6ml / 0.2 oz",
        keywords="Al Rehab, Diala, Perfume Oil, Roll-On, Women, 6ml, 0.2 oz, Peach, Mango, Vanilla, Musk",
        highlights=[
            "Concentrated perfume oil roll-on format.",
            "Women's fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Soft tropical-fruity floral profile with creamy vanilla finish.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product plus the exact 6ml oil naming in the title. This pass fills missing structure and SDS without inventing new source claims.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=12,
        barcode="6291110112392",
        brand="Al Rehab",
        name="Al Rehab Jourie Perfume Oil Roll-On 6ml (0.2 oz) Women Perfume",
        gender="Women",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A romantic women's perfume oil with bright citrus and red fruits up top, elegant florals in the heart, and musky ambergris sandalwood depth in the base.",
        top_notes="Citrus, Red Fruits",
        mid_notes="Rose, Jasmine, Orange Blossom",
        base_notes="Musk, Ambergris, Sandalwood",
        scent="Floral fruity musky elegant",
        feature="perfume oil roll-on; women; 6ml / 0.2 oz",
        keywords="Al Rehab, Jourie, Perfume Oil, Roll-On, Women, 6ml, 0.2 oz, Rose, Jasmine, Musk, Sandalwood",
        highlights=[
            "Concentrated perfume oil roll-on format.",
            "Women's fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Elegant fruity-floral profile with musky woody depth.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already on the product plus the exact 6ml / 0.2 oz naming in the legacy title. This standardizes the structured fields and SDS attachment.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=28,
        barcode="6281110085291",
        brand="Al Rehab",
        name="Al Rehab Million Secrets Eau de Parfum Spray 50ml (1.69 oz) Women Perfume",
        gender="Women",
        size_oz=1.69,
        size_ml=50,
        volume_oz=1.69,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A polished women's eau de parfum with aromatic brightness up top, soft jasmine-peony florals in the heart, and a smooth vanilla-sandalwood musk base.",
        top_notes="Lavender, Aldehydes",
        mid_notes="Jasmine, Peony",
        base_notes="Vanilla, Sandalwood, Musk",
        scent="Powdery floral soft sweet",
        feature="eau de parfum spray; women; 50ml / 1.69 oz",
        keywords="Al Rehab, Million Secrets, Eau De Parfum, Women, 50ml, 1.69 oz, Lavender, Jasmine, Vanilla, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Al Rehab.",
            "50 mL / 1.69 oz bottle size.",
            "Soft floral-powdery profile with warm musky vanilla finish.",
        ],
        similar_to=None,
        verified_note="Completed from the existing verified note pyramid already stored on the product and the exact 50ml naming. This pass fills the missing size, title normalization, and SDS fields only.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=177,
        barcode="6290171072836",
        brand="Afnan",
        name="Afnan 9 AM Dive Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A fresh unisex eau de parfum with bright citrus and mint up top, airy aromatic woods through the heart, and a smooth spicy-woody base.",
        top_notes="Lemon, Pink Pepper, Mint, Black Currant",
        mid_notes="Apple, Incense, Cedar",
        base_notes="Patchouli, Jasmine, Ginger, Sandalwood",
        scent="Fresh citrus aromatic woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Afnan, 9 AM Dive, Eau De Parfum, Unisex, 100ml, 3.4 oz, Lemon, Mint, Cedar, Sandalwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-aromatic profile with woody spicy depth.",
        ],
        similar_to=None,
        verified_note="Previously source-verified from official Afnan, Fragrantica, Parfumo, and Jomashop. This pass just adds the missing SDS attachment while preserving the product's existing structured data.",
        source_official_url="https://us.afnan.com/products/9-am-dive",
        source_jomashop_url="https://www.jomashop.com/afnan-unisex-9-am-dive-edp-spray-3-4-oz-fragrances-6290171072836.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Afnan/9am-Dive-78611.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Afnan_Perfumes/9am-dive",
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
]


def main() -> int:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(json.dumps(results, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
