#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_tenth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=51,
        barcode="6291107455365",
        brand="Lattafa",
        name="Lattafa Qaed Al Fursan Eau de Parfum Spray 90ml (3 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.0,
        size_ml=90,
        volume_oz=3.0,
        volume_ml=90,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bold unisex eau de parfum with juicy pineapple and saffron up top, a woody floral heart, and a warm oud-amber base.",
        top_notes="Pineapple, Saffron",
        mid_notes="Balsam Fir, Jasmine",
        base_notes="Amber, Cedar, Agarwood",
        scent="Fruity woody sweet smoky",
        feature="eau de parfum spray; unisex; 90ml / 3 oz",
        keywords="Lattafa, Qaed Al Fursan, Eau De Parfum, Unisex, 90ml, 3 oz, Pineapple, Saffron, Jasmine, Agarwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "90 mL / 3 oz bottle size.",
            "Pineapple-forward fruity-woody profile with warm oud and amber depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, Parfumo, and Jomashop listing support. The scent profile is consistently described as a fruity pineapple-led woody composition that works well in warm weather, casual wear, and mass-appeal everyday use.",
        source_official_url="https://www.lattafa-usa.com/products/qaed-al-fursan",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Qaed-Al-Fursan-67996.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/qaed-al-fursan",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_9fb3182c-ce4b-4238-ac54-ed0498a19be6.png?v=1747501113",
            "https://fimgs.net/mdimg/perfume/375x500.67996.jpg",
        ],
        official_discrepancy_note="Lattafa USA and the major fragrance references classify Qaed Al Fursan for women and men, while some retailer listings narrow it to men's marketing.",
    ),
    ProductSeed(
        product_id=268,
        barcode="6290362340645",
        brand="Lattafa",
        name="Lattafa Qaed Al Fursan Untamed Eau de Parfum Spray 90ml (3 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.0,
        size_ml=90,
        volume_oz=3.0,
        volume_ml=90,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A spicy unisex eau de parfum with cinnamon-cardamom brightness, a caramel aromatic heart, and a resinous amber-cedar base.",
        top_notes="Cinnamon, Cardamom, Mandarin, Nutmeg",
        mid_notes="Caramel, Lavender, Clary Sage, Geranium, Cypress",
        base_notes="Amber, Cedarwood, Olibanum, Labdanum, Vetiver",
        scent="Warm spicy amber woody aromatic",
        feature="eau de parfum spray; unisex; 90ml / 3 oz",
        keywords="Lattafa, Qaed Al Fursan Untamed, Eau De Parfum, Unisex, 90ml, 3 oz, Cinnamon, Cardamom, Caramel, Vetiver",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "90 mL / 3 oz bottle size.",
            "Spicy caramel-amber style with woody resinous depth.",
        ],
        similar_to=None,
        verified_note="Verified from Fragrantica, Parfumo, Jomashop, and exact-barcode retailer support. The profile lands in a warm spicy woody lane that reads best in cooler weather, evenings, and date-night style wear.",
        source_official_url="https://www.lattafa-usa.com/products/qaed-al-fursan-unlimited",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-untamed-qaed-al-fursan-edp-spray-3-0-oz-fragrances-6290362340645.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Qaed-Al-Fursan-Untamed-105383.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/qaed-al-fursan-untamed",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Qaed-Al-Fursan-Untamed-1_85250e2a-2ec7-4f49-9612-1161bec0e54b.png?v=1747417147",
            "https://fimgs.net/mdimg/perfume/375x500.105383.jpg",
        ],
        official_discrepancy_note="Lattafa USA currently exposes the Untamed bottle under the old qaed-al-fursan-unlimited slug, and the notes shown there conflict with the exact-barcode fragrance pages, so the saved pyramid follows Fragrantica, Parfumo, and exact-barcode retailer data.",
    ),
    ProductSeed(
        product_id=147,
        barcode="6291107450605",
        brand="Lattafa",
        name="Lattafa Qimmah Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy women's eau de parfum with almond-coffee sparkle, a white floral tonka heart, and a smooth vanilla-cacao sandalwood base.",
        top_notes="Almond, Coffee",
        mid_notes="Jasmine, Tuberose, Tonka Bean",
        base_notes="Vanilla, Cacao, Sandalwood",
        scent="White floral vanilla almond sweet",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Qimmah, Eau De Parfum, Women, 100ml, 3.4 oz, Almond, Coffee, Tuberose, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy white-floral gourmand profile with vanilla and cacao warmth.",
        ],
        similar_to="Carolina Herrera Good Girl",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most often points toward the Good Girl lane, with source-backed wear guidance favoring date nights, cooler weather, and feminine sweet-floral wear.",
        source_official_url="https://www.lattafa-usa.com/products/qimmah",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-qimmah-edp-spray-3-4-oz-fragrances-6291107450605.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Qimmah-for-Women-82793.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/qimmah-for-women",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_e42e4d3e-a719-4178-9bb0-6e998d1973ae.png?v=1747498725",
            "https://fimgs.net/mdimg/perfume/375x500.82793.jpg",
        ],
    ),
    ProductSeed(
        product_id=169,
        barcode="6291107456485",
        brand="Lattafa",
        name="RAVE Now Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fruity men's eau de parfum with pineapple and blackcurrant on top, a rosy birch-patchouli heart, and a musky vanilla oakmoss base.",
        top_notes="Pineapple, Bergamot, Apple, Black Currant",
        mid_notes="Birch, Patchouli, Moroccan Jasmine, Rose",
        base_notes="Musk, Vanilla, Oakmoss, Ambergris",
        scent="Fruity sweet woody fresh",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="RAVE, Now, Eau De Parfum, Men, 100ml, 3.4 oz, Pineapple, Black Currant, Birch, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from RAVE by Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fruity fresh style with pineapple, birch, and musky vanilla depth.",
        ],
        similar_to=None,
        verified_note="Verified from Fragrantica, Parfumo, Jomashop, and archived Lattafa USA retailer coverage. The profile is consistently presented as a fruity pineapple-led masculine scent that fits casual wear, spring/summer, and easy crowd-pleasing use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-rave-now-edp-spray-3-4-oz-fragrances-6291107456485.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/RAVE/Now-82467.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Rave/now",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.82467.jpg",
        ],
        official_discrepancy_note="An older Lattafa USA product snapshot exists for this barcode, but the direct page is no longer live. Some wholesalers market it as unisex, while Fragrantica and Parfumo consistently place it in the men's RAVE line.",
    ),
    ProductSeed(
        product_id=200,
        barcode="6291108735053",
        brand="Lattafa",
        name="RAVE Now Intense Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fresh men's eau de parfum with watery tangerine-cucumber brightness, an herbal sage-basil core, and a woody leathered base.",
        top_notes="Cucumber, Watermelon, Tangerine",
        mid_notes="Basil, Sage",
        base_notes="Sandalwood, Leather, Cedar",
        scent="Fresh aquatic woody aromatic",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="RAVE, Now Intense, Eau De Parfum, Men, 100ml, 3.4 oz, Cucumber, Watermelon, Sage, Leather",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from RAVE by Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh watery opening with herbal heart and woody leather drydown.",
        ],
        similar_to=None,
        verified_note="Verified from Fragrantica, Parfumo, Jomashop listing support, and exact-barcode retailer data. The profile reads as a fresh masculine daily scent that works best in warm weather, daytime wear, and casual rotation.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/RAVE/Now-Intense-82468.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Rave/now-intense",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.82468.jpg",
        ],
        official_discrepancy_note="An older Lattafa USA product snapshot for this barcode is no longer directly live, and Jomashop metadata still labels the item as EDT in some feeds, but the fragrance references and exact-barcode retailer pages support the saved note pyramid and EDP positioning.",
    ),
    ProductSeed(
        product_id=47,
        barcode="6290360590349",
        brand="Lattafa",
        name="RAVE Now White Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright unisex eau de parfum with sparkling grapefruit and bergamot, a crisp green-apple patchouli heart, and a musky amber-cashmeran finish.",
        top_notes="Grapefruit, Bergamot",
        mid_notes="Green Apple, Patchouli",
        base_notes="Musk, Cashmeran, Amber",
        scent="Fresh citrus fruity musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="RAVE, Now White, Eau De Parfum, Unisex, 100ml, 3.4 oz, Grapefruit, Green Apple, Patchouli, Cashmeran",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from RAVE by Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Clean citrus-fruity profile with musky amber softness.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop listing support, Fragrantica, and Parfumo. Source-backed wear guidance places it in the fresh easygoing lane, working best for spring and summer daytime use.",
        source_official_url="https://www.lattafa-usa.com/products/rave-now-white",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-rave-now-white-edp-spray-3-4-oz-fragrances-6290360590349.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/RAVE/Now-White-85089.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Rave/now-white",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_1282228f-d6e2-44b8-865d-4a1bd4bc65d6.png?v=1749496242",
            "https://fimgs.net/mdimg/perfume/375x500.85089.jpg",
        ],
        official_discrepancy_note="Some secondary retailers show a brighter lemon-jasmine-cedar style pyramid, but the current Lattafa USA page and broader fragrance references support the grapefruit, green apple, patchouli, and cashmeran structure saved here.",
    ),
    ProductSeed(
        product_id=163,
        barcode="6290360595764",
        brand="Lattafa",
        name="Lattafa Teriaq Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich unisex eau de parfum with caramelized apricot spice up top, a honeyed floral-rhubarb heart, and a smooth leathery vanilla base.",
        top_notes="Caramel, Apricot, Bitter Almond, Pink Pepper",
        mid_notes="Honey, White Flowers, Rhubarb, Rose",
        base_notes="Labdanum, Leather, Vanilla, Musk, Vetiver",
        scent="Sweet gourmand leathery spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Teriaq, Eau De Parfum, Unisex, 100ml, 3.4 oz, Caramel, Honey, Rhubarb, Leather",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet gourmand profile with honeyed florals and leathery vanilla depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Most source-backed wear guidance points to a richer sweet-gourmand style that shines in cooler weather, evenings, and statement wear.",
        source_official_url="https://www.lattafa-usa.com/products/teriaq",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-teriaq-edp-spray-3-4-oz-fragrances-6290360595764.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Teriaq-89850.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/teriaq-eau-de-parfum",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Teriaq-1_9cd52e8c-943a-4aa4-be16-2a30638fc421.png?v=1747416456",
            "https://fimgs.net/mdimg/perfume/375x500.89850.jpg",
        ],
        official_discrepancy_note="Parfumo currently frames Teriaq as a women's release, while Lattafa USA, Fragrantica, Jomashop, and broader marketplace coverage support a wider unisex presentation.",
    ),
    ProductSeed(
        product_id=159,
        barcode="6290360595771",
        brand="Lattafa",
        name="Lattafa Teriaq Intense Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A dense unisex eau de parfum with saffron and bergamot up top, a boozy plum-cinnamon heart, and a warm amber-tonka benzoin base.",
        top_notes="Saffron, Bergamot",
        mid_notes="Plum Liquor, Cinnamon",
        base_notes="Amber, Tonka Bean, Benzoin",
        scent="Amber warm spicy fruity boozy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Teriaq Intense, Eau De Parfum, Unisex, 100ml, 3.4 oz, Saffron, Plum Liquor, Cinnamon, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Boozy spiced amber style with rich plum and tonka warmth.",
        ],
        similar_to="Borntostandout Drunk Saffron",
        verified_note="Verified from Lattafa USA, Fragrantica, Parfumo, Jomashop listing support, and exact-barcode retailer data. Community comparison most often points toward the Drunk Saffron lane, and the source-backed wear fit is cooler weather, evenings, and richer sweet-spicy use.",
        source_official_url="https://www.lattafa-usa.com/products/teriaq-intense",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-teriaq-intense-edt-spray-3-4-oz-fragrances-6290360595771.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Teriaq-Intense-99586.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/teriaq-intense",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Teriaq-Intense-1_b9408dff-5346-4542-a598-cfffb8454d81.png?v=1747416499",
            "https://fimgs.net/mdimg/perfume/375x500.99586.jpg",
        ],
        official_discrepancy_note="Some retailer feeds still label this UPC as EDT, but the current Lattafa USA page, Fragrantica, Parfumo, and exact-barcode reseller data all support Eau de Parfum.",
    ),
    ProductSeed(
        product_id=58,
        barcode="6290360598352",
        brand="Lattafa",
        name="Lattafa The Kingdom Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A feminine eau de parfum with pear and blackcurrant sparkle, a sweet jasmine-praline heart, and a creamy vanilla-musk sandalwood base.",
        top_notes="Pear, Blackcurrant, Peony",
        mid_notes="Jasmine, Tonka Bean, Praline",
        base_notes="Sandalwood, Vanilla, Amber, Musk",
        scent="Fruity sweet floral musky",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, The Kingdom, Eau De Parfum, Women, 100ml, 3.4 oz, Pear, Blackcurrant, Praline, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet fruity-floral profile with creamy vanilla musk warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to a sweet feminine style that works especially well in fall and winter, evenings, and easy crowd-pleasing daily wear.",
        source_official_url="https://www.lattafa-usa.com/products/the-kingdom-women",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-the-kingdom-edp-spray-3-4-oz-fragrances-6290360598352.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/The-Kingdom-For-Women-98648.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/the-kingdom-for-women",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/IMG-1625.png?v=1756740801",
            "https://fimgs.net/mdimg/perfume/375x500.98648.jpg",
        ],
    ),
    ProductSeed(
        product_id=214,
        barcode="6290360598345",
        brand="Lattafa",
        name="Lattafa The Kingdom Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich men's eau de parfum with lavender-mint freshness, a smooth tobacco-vanilla heart, and a sweet resinous tonka base.",
        top_notes="Lavender, Mint, Sage",
        mid_notes="Vanilla, Tobacco, Orange Blossom",
        base_notes="Tonka Bean, Benzoin, Labdanum",
        scent="Vanilla aromatic sweet tobacco",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, The Kingdom, Eau De Parfum, Men, 100ml, 3.4 oz, Lavender, Tobacco, Vanilla, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Aromatic vanilla-tobacco profile with sweet resinous depth.",
        ],
        similar_to="Jean Paul Gaultier Le Male Elixir",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most often points toward the Le Male Elixir lane, and the source-backed wear fit is fall/winter, evenings, and sweet aromatic masculine use.",
        source_official_url="https://www.lattafa-usa.com/products/the-kingdom",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-the-kingdom-edp-spray-3-4-oz-fragrances-6290360598345.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/The-Kingdom-For-Men-97995.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/the-kingdom-for-men",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/The-Kingdom-Men-1_ecd1b262-1319-4fee-846b-8b6f30939677.png?v=1747416549",
            "https://fimgs.net/mdimg/perfume/375x500.97995.jpg",
        ],
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
