#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_fourth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=266,
        barcode="6290360591513",
        brand="Lattafa",
        name="Lattafa Jasoor Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A smooth sweet-spicy fragrance with crisp cardamom fruitiness up top, aromatic tobacco through the heart, and a warm leathery tonka base.",
        top_notes="Apple, Cardamom, Bergamot",
        mid_notes="Lavender, Tobacco, Geranium",
        base_notes="Patchouli, Leather, Vetiver, Tonka Bean",
        scent="Sweet fruity spicy aromatic",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Jasoor, Eau De Parfum, Unisex, 100ml, 3.4 oz, Apple, Cardamom, Tobacco, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Shared-wear fragrance from Lattafa with a masculine-leaning profile.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet spicy-fruity profile with tobacco, leather, and tonka warmth.",
        ],
        similar_to="Valentino Uomo Born In Roma Coral Fantasy",
        verified_note="Verified from Lattafa official, Fragrantica, Parfumo, and Jomashop. Versatile sweet-spicy fruity scent with strong mass appeal; best source-backed wear guidance leans date nights, casual evenings, and cooler-weather use while still staying easy enough for everyday wear.",
        source_official_url="https://lattafa.com/product/jasoor/",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-jasoor-edp-spray-3-4-oz-fragrances-6290360591513.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Jasoor-85093.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/jasoor",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-jasoor-edp-spray-34-oz-fragrances-6290360591513.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.85093.jpg",
        ],
        official_discrepancy_note="Lattafa's official page mixes two note presentations on the same product, but the Apple/Cardamom/Bergamot pyramid aligns with Fragrantica, Parfumo, Jomashop, and the official product-information text, so that aligned version was saved.",
    ),
    ProductSeed(
        product_id=144,
        barcode="6290362340546",
        brand="Maison Alhambra",
        name="Maison Alhambra Jean Lowe Azure Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright citrus fragrance with sparkling mandarin and bergamot, a refined floral-woody heart, and a smooth ambergris-musky finish.",
        top_notes="Bergamot, Mandarin",
        mid_notes="Jasmine, Cedarwood",
        base_notes="Ambergris, Musk",
        scent="Fresh citrus musky aromatic",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Jean Lowe Azure, Eau De Parfum, Unisex, 100ml, 3.4 oz, Bergamot, Mandarin, Jasmine, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-musky profile with airy woody refinement.",
        ],
        similar_to="Louis Vuitton Afternoon Swim",
        verified_note="Verified from Maison Alhambra USA, Fragrantica, and the Jomashop listing trail. Fresh citrus-focused unisex scent best suited to warm weather, daytime wear, and easy casual use; performance expectations should stay in the lighter fresh-fragrance lane.",
        source_official_url="https://maisonalhambra-usa.com/products/maison-alhambra-jean-lowe-azure-eau-de-parfum-for-everyone",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Jean-Lowe-Azure-100480.html",
        source_parfumo_url=None,
        image_sources=[
            "https://maisonalhambra-usa.com/cdn/shop/files/01tfzvgbzd_533x.png?v=1753478107",
            "https://maisonalhambra-usa.com/cdn/shop/files/02giuemv94_533x.png?v=1753478112",
            "https://fimgs.net/mdimg/perfume/375x500.100480.jpg",
        ],
        official_discrepancy_note="Maison Alhambra USA currently lists a Bergamot/Mandarin/Jasmine/Cedarwood/Ambergris/Musk structure, while Fragrantica shows a Mandarin/Orange/Ginger/Ambergris interpretation; the saved record follows the exact official product page.",
    ),
    ProductSeed(
        product_id=178,
        barcode="6291108735541",
        brand="Maison Alhambra",
        name="Maison Alhambra Jean Lowe Immortel Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A sharp citrus-aromatic men's fragrance with grapefruit and ginger brightness, watery herbal depth, and an ambery ambroxan drydown.",
        top_notes="Grapefruit, Ginger, Bergamot",
        mid_notes="Rosemary, Aquatic Notes, Sage, Geranium",
        base_notes="Ambroxan, Amber, Labdanum",
        scent="Fresh citrus aromatic amber",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Jean Lowe Immortel, Eau De Parfum, Men, 100ml, 3.4 oz, Grapefruit, Ginger, Sage, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-aromatic profile with ambery ambroxan depth.",
        ],
        similar_to="Louis Vuitton L'Immensité",
        verified_note="Verified from Maison Alhambra USA, Lattafa Morocco, and Fragrantica. Fresh citrus-ginger masculine scent with strong signature-scent versatility; best source-backed use cases include warm weather, office, everyday wear, and polished casual evenings.",
        source_official_url="https://maisonalhambra-usa.com/products/maison-alhambra-jean-lowe-immortal-eau-de-parfum-for-men",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Jean-Lowe-Immortal-83666.html",
        source_parfumo_url=None,
        image_sources=[
            "https://maisonalhambra-usa.com/cdn/shop/files/016h20dk7b_533x.png?v=1731453560",
            "https://maisonalhambra-usa.com/cdn/shop/files/02lnzjn8qj_533x.png?v=1731453563",
            "https://fimgs.net/mdimg/perfume/375x500.83666.jpg",
        ],
    ),
    ProductSeed(
        product_id=179,
        barcode="6291108735558",
        brand="Maison Alhambra",
        name="Maison Alhambra Jean Lowe Matiere Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A floral-amber woody fragrance built around white florals, rose, and incense-darkened woods with a smooth elegant finish.",
        top_notes="Jasmine, Narcissus",
        mid_notes="Rose, Cyclamen",
        base_notes="Agarwood (Oud), Patchouli, Incense",
        scent="Rose oud floral amber",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Jean Lowe Matiere, Eau De Parfum, Unisex, 100ml, 3.4 oz, Jasmine, Rose, Oud, Incense",
        highlights=[
            "Eau de parfum spray concentration.",
            "Shared-wear floral-amber woody fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Rose, oud, and incense profile with a refined floral opening.",
        ],
        similar_to=None,
        verified_note="Verified from Maison Alhambra USA, Fragrantica, and Jomashop listing data. Elegant rose-oud incense scent with a more dressed-up feel; strongest source-backed guidance points to cooler weather, evening wear, and users who enjoy richer floral-woody profiles.",
        source_official_url="https://maisonalhambra-usa.com/products/maison-alhambra-jean-lowe-matiere-eau-de-parfum-for-everyone",
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-mens-jean-lowe-matiere-edp-3-4-oz-fragrances-6291108735558.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Jean-Lowe-Matiere-94060.html",
        source_parfumo_url=None,
        image_sources=[
            "https://maisonalhambra-usa.com/cdn/shop/files/03rxksbcvv_533x.png?v=1731453568",
            "https://maisonalhambra-usa.com/cdn/shop/files/04bamksuuz_533x.png?v=1731453571",
            "https://maisonalhambra-usa.com/cdn/shop/files/03vdkf3u87_533x.jpg?v=1731453573",
            "https://fimgs.net/mdimg/perfume/375x500.94060.jpg",
        ],
        official_discrepancy_note="Maison Alhambra USA presents this barcode as 'for everyone', while Fragrantica frames it for women and some retailer trails place it in men's sections. The saved record uses a unisex classification because the source set is split.",
    ),
    ProductSeed(
        product_id=142,
        barcode="6290362340553",
        brand="Maison Alhambra",
        name="Maison Alhambra Jean Lowe Vibe Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A lively citrus-aromatic fragrance with mint and bright fruit in the opening, an apricot-rose heart, and a soft fig-ambrette base.",
        top_notes="Mint, Citron, Lemon, Coriander, Orange, Black Currant",
        mid_notes="Apricot, Carrot Seeds, May Rose, Basil",
        base_notes="Fig, Ambrette, Dates",
        scent="Citrus fruity aromatic green",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Jean Lowe Vibe, Eau De Parfum, Men, 100ml, 3.4 oz, Mint, Citron, Apricot, Fig",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-fruity profile with fig, ambrette, and aromatic herbs.",
        ],
        similar_to="Louis Vuitton Pacific Chill",
        verified_note="Verified from Lattafa Morocco, Fragrantica, and Jomashop. Bright citrus-fruity scent with a warm-weather, daytime, and vacation-style personality; source-backed impressions consistently place it in the fresh casual summer lane.",
        source_official_url="https://www.lattafa.ma/jean-lowe-vibe",
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-unisex-jean-lowe-vibe-edp-spray-3-4-oz-fragrances-6290362340553.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Jean-Lowe-Vibe-103352.html",
        source_parfumo_url=None,
        image_sources=[
            "https://maisonalhambra.co/wp-content/uploads/2026/01/edited_2-3-min.webp",
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/m/a/maison-alhambra-unisex-jean-lowe-vibe-edp-spray-34-oz-fragrances-6290362340553.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.103352.jpg",
        ],
        official_discrepancy_note="Lattafa Morocco classifies Jean Lowe Vibe in its men's catalog, while Fragrantica presents it for women and men. The saved record follows the exact official product classification.",
    ),
    ProductSeed(
        product_id=166,
        barcode="6291108730140",
        brand="Maison Alhambra",
        name="Maison Alhambra Jorge Di Profumo Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fresh aromatic men's fragrance built on citrus, pepper, lavender, and tobacco over a musky woody base.",
        top_notes="Bergamot, Black Pepper, Sicilian Lemon",
        mid_notes="Lavender, Tobacco, Geranium",
        base_notes="Sandalwood, Vetiver, Musk",
        scent="Fresh spicy aromatic woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Jorge Di Profumo, Eau De Parfum, Men, 100ml, 3.4 oz, Bergamot, Tobacco, Vetiver, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh spicy-aquatic-woody profile with tobacco in the heart.",
        ],
        similar_to="Giorgio Armani Acqua di Giò Profumo",
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop. Fresh aromatic masculine scent with a clean everyday structure; best source-backed use cases are daily wear, office wear, gym, and warm-weather casual use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-mens-jorge-di-profumo-edp-spray-3-4-oz-fragrances-6291108730140.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Jorge-di-Profumo-92629.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/maison-alhambra/jorge-di-profumo",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/m/a/maison-alhambra-mens-jorge-di-profumo-edp-spray-3-4-oz-fragrances-6291108730140.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.92629.jpg",
        ],
    ),
    ProductSeed(
        product_id=267,
        barcode="6290362342373",
        brand="Lattafa",
        name="Lattafa Khamrah Dukhan Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A dark smoky gourmand fragrance with spiced mandarin in the opening, resinous florals through the heart, and a rich tobacco-praline amber base.",
        top_notes="Spices, Pimento, Mandarin",
        mid_notes="Incense, Labdanum, Orange Blossom, Patchouli",
        base_notes="Tobacco, Praline, Amber, Tonka Bean, Benzoin",
        scent="Amber warm spicy tobacco smoky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Khamrah Dukhan, Eau De Parfum, Unisex, 100ml, 3.4 oz, Pimento, Incense, Tobacco, Praline",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa with a masculine-leaning profile.",
            "100 mL / 3.4 oz bottle size.",
            "Smoky amber-tobacco gourmand profile with praline depth.",
        ],
        similar_to="Lattafa Khamrah / Lattafa Khamrah Qahwa",
        verified_note="Verified from Lattafa official, Fragrantica, Parfumo, and Jomashop. Dense smoky-spiced gourmand with clear cooler-weather and nighttime strength; source-backed usage leans fall/winter evenings, parties, and bold statement wear.",
        source_official_url="https://lattafa.com/product/khamrah-dukhan/",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-khamrah-dukhan-edp-spray-3-4-oz-fragrances-6290362342373.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-Dukhan-104529.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/khamrah-dukhan",
        image_sources=[
            "https://www.lattafa-usa.com/cdn/shop/files/Khamrah-Dukhan-1_a62cb1af-0737-4709-86c2-f275a5f5b023.png?v=1747416848",
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-khamrah-dukhan-edp-spray-34-oz-fragrances-6290362342373.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.104529.jpg",
        ],
        official_discrepancy_note="Lattafa presents Khamrah Dukhan as unisex with a masculine angle, while some retailers file it strictly under men's fragrance. The saved record keeps the unisex classification from the brand.",
    ),
    ProductSeed(
        product_id=182,
        barcode="6291107451527",
        brand="Lattafa",
        name="Lattafa Lail Maleki Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich oriental floral fragrance with warm fruity spice in the opening, honeyed white florals at the heart, and a smooth caramel-amber base.",
        top_notes="Fruity Notes, Citrus, Spices",
        mid_notes="Jasmine, Gardenia, Honey, Orchid",
        base_notes="Musk, Sandalwood, Amber, Caramel",
        scent="White floral sweet honey amber",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Lail Maleki, Eau De Parfum, Unisex, 100ml, 3.4 oz, Honey, Jasmine, Orchid, Caramel",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Oriental floral-honey profile with amber and caramel warmth.",
        ],
        similar_to="Khalis Jawad Al Layl",
        verified_note="Verified from Lattafa official, Lattafa USA, Fragrantica, and Parfumo. Rich sweet-floral oriental with strong evening energy; source-backed guidance points to special occasions, festive wear, and cooler-weather or nighttime use rather than everyday office wear.",
        source_official_url="https://lattafa.com/product/lail-maleki/",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Lail-Maleki-59133.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/lail-maleki",
        image_sources=[
            "https://www.giftexpress.com/media/catalog/product/cache/8707a82ff53728be6dbcd7cea0f577d3/g/x/gxp-11571.jpg",
            "https://fimgs.net/mdimg/perfume/375x500.59133.jpg",
        ],
        official_discrepancy_note="Lattafa's own pages mix a broad 'fruity/citrus/spices' presentation with a more specific pineapple/aldehydes/cinnamon pyramid on different surfaces. The saved record follows the exact brand-description version that aligns with Lattafa USA and Fragrantica.",
    ),
    ProductSeed(
        product_id=204,
        barcode="6290362342489",
        brand="Lattafa",
        name="Lattafa Lail Maleki Moroccan Blue Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fresh-spicy woody fragrance with bergamot and citrus at the top, clean amber-musk florals through the heart, and a dry oud-sandalwood base.",
        top_notes="Aromatic Spices, Bergamot, Citrus",
        mid_notes="Amber, Floral Notes, Musk",
        base_notes="Agarwood, Oud, Patchouli, Sandalwood",
        scent="Fresh spicy woody musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Lail Maleki Moroccan Blue, Eau De Parfum, Unisex, 100ml, 3.4 oz, Bergamot, Amber, Musk, Sandalwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa with a masculine-leaning blue-fresh style.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh spicy-woody profile with oud depth and clean musky lift.",
        ],
        similar_to="Parfums de Marly Sedley / Parfums de Marly Percival",
        verified_note="Verified from Lattafa USA, Lattafa Morocco, Fragrantica, and Parfumo. Fresh spicy blue-woody scent with strong summer and everyday versatility; source-backed wear guidance points to casual wear, errands, sports, office, and warm-weather daytime use.",
        source_official_url="https://lattafa-usa.com/products/lattafa-lail-maleki-moroccan-blue-eau-de-parfum-for-everyone",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Lail-Maleki-Moroccan-Blue-107705.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/lail-maleki-moroccan-blue",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/0ee3019724ce73007b606b54ba535a23/l/a/lattafa-unisex-lail-maleki-morrocan-blue-edp-spray-34-oz-fragrances-6290362342489.jpg?width=546&height=546",
            "https://fimgs.net/mdimg/perfume/375x500.107705.jpg",
        ],
        official_discrepancy_note="The official Lattafa pages use 'for everyone' framing while also describing Moroccan Blue as a men's oriental woody scent. The saved record keeps the unisex classification but notes its masculine-leaning profile.",
    ),
    ProductSeed(
        product_id=228,
        barcode="6290362348085",
        brand="Lattafa Pride",
        name="Lattafa Pride 5 x 20ml Gift Set (Art of Arabia III Edition) 100ml (3.38 oz) Unisex Fragrance Set",
        gender="Unisex",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A five-piece mini fragrance gift set designed for discovery, travel, and gifting, featuring curated Lattafa Pride scents in 20ml spray bottles.",
        top_notes="Varies by included fragrance in the set",
        mid_notes="Varies by included fragrance in the set",
        base_notes="Varies by included fragrance in the set",
        scent="Mixed discovery set",
        feature="5 x 20ml eau de parfum sprays; unisex fragrance gift set; total 100ml",
        keywords="Lattafa Pride, Mini Gift Set, Art of Arabia III, Ajwaa, Al Qiam Gold, Masa, Brioche Vanille, 5x20ml",
        highlights=[
            "Gift set with five 20 mL mini fragrance sprays.",
            "Lattafa Pride unisex discovery-style set.",
            "Total fill volume 100 mL / 3.38 oz.",
            "Includes Art of Arabia III, Ajwaa, Al Qiam Gold, Masa, and Brioche Vanille.",
        ],
        similar_to=None,
        verified_note="Verified from multiple retailer sources tied to the barcode. This is a mixed mini set rather than a single fragrance pyramid, making it best for gifting, sampling, travel, or trying multiple Lattafa Pride profiles without committing to full bottles.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mini-set-gift-set-fragrances-6290362348085.html",
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mini-set-gift-set-fragrances-6290362348085.jpg?width=800&height=800",
        ],
        official_discrepancy_note="The Art of Arabia III Edition set contents were verified from retailer mirrors tied to the barcode rather than from an exact official Lattafa product page for this specific gift set.",
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
