#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (  # noqa: E402
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_remainder02_report.json"

COMMON_OIL_INGREDIENTS = "Parfum (Fragrance), carrier oils, fixatives, and stabilizers."
COMMON_SPRAY_INGREDIENTS = "Alcohol Denat., Parfum (Fragrance), Aqua (Water), fragrance compounds, fixatives, and stabilizers."


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=185,
        barcode="6290171072591",
        brand="Afnan",
        name="Afnan 9 AM Pour Femme Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A radiant women's eau de parfum with sparkling citrus top notes, a fruity heart, and a soft amber-musk finish.",
        top_notes="Mandarin, Bergamot, Grapefruit",
        mid_notes="Black Currant, Raspberry",
        base_notes="Musk, Orange, Amber",
        scent="Fruity citrus amber musky",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Afnan, 9 AM Pour Femme, Eau De Parfum, Women, 100ml, 3.4 oz, Mandarin, Raspberry, Amber, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Bright fruity-citrus profile with soft amber-musk finish.",
        ],
        similar_to=None,
        verified_note="Previously source-verified from official Afnan, Jomashop, and fragrance-reference pages. This pass adds the missing SDS while preserving the existing structured notes and sizing.",
        source_official_url="https://us.afnan.com/products/9am-pour-femme",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=193,
        barcode="6290171075738",
        brand="Afnan",
        name="Afnan 9 PM Elixir Extrait de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Extrait De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A warm and magnetic unisex extrait de parfum with a spicy opening, a smooth aromatic-leather heart, and a rich resinous vanilla base.",
        top_notes="Nutmeg, Elemi, Cardamome",
        mid_notes="Pimento, Lavandin, Leather",
        base_notes="Ciste, Labdanum, Patchouli, Vanilla",
        scent="Warm spicy leathery vanilla resinous",
        feature="extrait de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Afnan, 9 PM Elixir, Extrait De Parfum, Unisex, 100ml, 3.4 oz, Nutmeg, Leather, Labdanum, Vanilla",
        highlights=[
            "Extrait de parfum spray concentration.",
            "Unisex fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Spicy leathery profile with rich vanilla-labdanum depth.",
        ],
        similar_to=None,
        verified_note="Previously source-verified from official Afnan, Jomashop, and fragrance-reference pages. This completion pass adds the missing SDS only.",
        source_official_url="https://us.afnan.com/products/9-pm-elixir",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=209,
        barcode="6290171072607",
        brand="Afnan",
        name="Afnan 9 PM Pour Femme Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A bold women's eau de parfum with juicy fruit up top, lush florals through the heart, and a warm woody-amber finish.",
        top_notes="Raspberry, Apple, Violet, Orange",
        mid_notes="Rose, Peony, Iris, Jasmine",
        base_notes="Cedar, Cypress, Pine Tree, Amber",
        scent="Fruity floral woody amber",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Afnan, 9 PM Pour Femme, Eau De Parfum, Women, 100ml, 3.4 oz, Raspberry, Rose, Cedar, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Juicy floral profile with woody amber finish.",
        ],
        similar_to=None,
        verified_note="Previously source-verified from official Afnan, Jomashop, and fragrance-reference pages. This pass adds the missing SDS while keeping the existing data intact.",
        source_official_url="https://us.afnan.com/products/9pm-pour-femme",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=192,
        barcode="6290171075288",
        brand="Afnan",
        name="Afnan 9 PM Rebel Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A sophisticated unisex eau de parfum with a fruity opening, a woody-vanillic heart, and a smooth amber-musk drydown.",
        top_notes="Mandarin, Pineapple, Granny Smith",
        mid_notes="Cedarwood, Oakmoss, Vanilla",
        base_notes="Caramel, Dry woods, Ambergris, Musk",
        scent="Fruity woody sweet musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Afnan, 9 PM Rebel, Eau De Parfum, Unisex, 100ml, 3.4 oz, Mandarin, Pineapple, Vanilla, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Fruity woody profile with vanilla and musky amber depth.",
        ],
        similar_to=None,
        verified_note="Previously source-verified from official Afnan, Jomashop, and fragrance-reference pages. This completion pass adds the missing SDS only.",
        source_official_url="https://us.afnan.com/products/9-pm-rebel",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=254,
        barcode="6291106814873",
        brand="Al Haramain",
        name="Al Haramain Amber Oud Aqua Dubai Extrait de Parfum Spray 100ml (3.38 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Extrait De Parfum",
        manufacturer="Al Haramain Perfumes LLC",
        description_intro="A fresh aromatic fruity extrait de parfum with a vibrant citrus opening and a smooth musky vanilla finish.",
        top_notes="Bergamot, Green notes, Mandarin orange",
        mid_notes="Amber, Black currant, Melon, Pineapple",
        base_notes="Galbanum, Musk, Petitgrain, Vanilla",
        scent="Fresh fruity aromatic musky",
        feature="extrait de parfum spray; unisex; 100ml / 3.38 oz",
        keywords="Al Haramain, Amber Oud Aqua Dubai, Extrait De Parfum, Unisex, 100ml, 3.38 oz, Bergamot, Pineapple, Musk, Vanilla",
        highlights=[
            "Extrait de parfum spray concentration.",
            "Unisex fragrance from Al Haramain.",
            "100 mL / 3.38 oz bottle size.",
            "Bright fruity-fresh profile with soft musky vanilla base.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and title-based size data. This pass fills the missing structured size fields and SDS attachment without forcing new claims.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=253,
        barcode="6291106813029",
        brand="Al Haramain",
        name="Al Haramain Amber Oud Ruby Eau de Parfum Spray 60ml (2.0 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=2.0,
        size_ml=60,
        volume_oz=2.0,
        volume_ml=60,
        product_form="Eau De Parfum",
        manufacturer="Al Haramain Perfumes LLC",
        description_intro="A rich unisex amber floral fragrance with a warm, luxurious character and a smooth woody-musky finish.",
        top_notes="Bitter almond, Saffron",
        mid_notes="Cedar, Egyptian jasmine",
        base_notes="Ambergris, Musk, Woody notes",
        scent="Amber floral woody musky",
        feature="eau de parfum spray; unisex; 60ml / 2.0 oz",
        keywords="Al Haramain, Amber Oud Ruby, Eau De Parfum, Unisex, 60ml, 2.0 oz, Saffron, Jasmine, Musk, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Haramain.",
            "60 mL / 2.0 oz bottle size.",
            "Warm amber-floral style with smooth woody-musky finish.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and the exact 60ml / 2.0 oz title. This pass fills the missing structure and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=22,
        barcode="6291110091642",
        brand="Al Rehab",
        name="Al Rehab Choco Musk Eau de Parfum Spray 50ml (1.65 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=1.65,
        size_ml=50,
        volume_oz=1.65,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A beloved unisex gourmand eau de parfum with milky chocolate and vanilla on top, warm cinnamon-rose musk in the heart, and a cozy sandalwood-amber base.",
        top_notes="Milk Chocolate, Vanilla, Spices",
        mid_notes="Cinnamon, Rose, Musk",
        base_notes="Sandalwood, Myrrh, Amber",
        scent="Chocolate vanilla gourmand warm",
        feature="eau de parfum spray; unisex; 50ml / 1.65 oz",
        keywords="Al Rehab, Choco Musk, Eau De Parfum, Unisex, 50ml, 1.65 oz, Chocolate, Vanilla, Cinnamon, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "50 mL / 1.65 oz bottle size.",
            "Comforting chocolate-vanilla gourmand profile.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and exact title-based size data. This pass fills missing structure and SDS fields without changing the scent story.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=6,
        barcode="6291110116284",
        brand="Al Rehab",
        name="Al Rehab Choco Musk Marshmallow Perfume Oil 6ml (0.2 oz) Women Perfume",
        gender="Women",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A sweet perfume oil with fluffy strawberry marshmallow on top, cozy amber through the heart, and warm vanilla-cacao musk in the base.",
        top_notes="Strawberry, Marshmallow",
        mid_notes="Amber",
        base_notes="Vanilla, Cacao, Musk",
        scent="Marshmallow sweet fruity gourmand",
        feature="perfume oil roll-on; women; 6ml / 0.2 oz",
        keywords="Al Rehab, Choco Musk Marshmallow, Perfume Oil, Women, 6ml, 0.2 oz, Strawberry, Marshmallow, Vanilla, Cacao",
        highlights=[
            "Concentrated perfume oil format.",
            "Women's fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Sweet marshmallow-cacao style with warm musky drydown.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing note pyramid and exact title-based size data. This pass adds the missing structure and SDS while preserving the original description.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=10,
        barcode="6291110091451",
        brand="Al Rehab",
        name="Al Rehab Choco Musk Perfume Oil 6ml (0.2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A cozy unisex perfume oil with creamy milk chocolate and vanilla on top, soft white musk and cinnamon through the heart, and warm sandalwood-amber depth below.",
        top_notes="Milk Chocolate, Vanilla",
        mid_notes="White Musk, Cinnamon, Rose",
        base_notes="Sandalwood, Amber, Myrrh",
        scent="Chocolate vanilla musky gourmand",
        feature="perfume oil roll-on; unisex; 6ml / 0.2 oz",
        keywords="Al Rehab, Choco Musk, Perfume Oil, Unisex, 6ml, 0.2 oz, Chocolate, Vanilla, Musk, Sandalwood",
        highlights=[
            "Concentrated perfume oil format.",
            "Unisex fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Creamy chocolate-vanilla profile ideal for layering.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and exact title-based size data. This pass fills the missing structured size, gender normalization, and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=24,
        barcode="6291110116291",
        brand="Al Rehab",
        name="Al Rehab Choco Musk Pistachio Eau de Parfum Spray 50ml (1.65 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=1.65,
        size_ml=50,
        volume_oz=1.65,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A sweet unisex gourmand eau de parfum with pistachio and musk on top, rich cacao through the heart, and a smooth vanilla-amber base.",
        top_notes="Pistachio, Musk",
        mid_notes="Cacao",
        base_notes="Vanilla, Amber",
        scent="Nutty gourmand sweet warm",
        feature="eau de parfum spray; unisex; 50ml / 1.65 oz",
        keywords="Al Rehab, Choco Musk Pistachio, Eau De Parfum, Unisex, 50ml, 1.65 oz, Pistachio, Cacao, Vanilla, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "50 mL / 1.65 oz bottle size.",
            "Nutty pistachio-cacao gourmand profile with warm vanilla-amber finish.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing note pyramid and exact title-based size data. This pass fills the missing structure and SDS fields while preserving the current product story.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
]


def main() -> int:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(json.dumps(results, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
