#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_ninth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=68,
        barcode="6291108732496",
        brand="Lattafa",
        name="Lattafa Mayar Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright women's eau de parfum with juicy berries and lychee up top, a fresh floral heart, and a soft musky vanilla base.",
        top_notes="Raspberry, Litchi, Violet Leaf",
        mid_notes="Peony, White Rose, Jasmine",
        base_notes="Musk, Vanilla",
        scent="Fruity floral sweet fresh",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Mayar, Eau De Parfum, Women, 100ml, 3.4 oz, Raspberry, Litchi, Peony, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Juicy fruity-floral profile with a soft musky vanilla finish.",
        ],
        similar_to=None,
        verified_note="Verified from Jomashop, Fragrantica, and Parfumo, with Lattafa-hosted barcode media support. Source-backed wear guidance points to an easy fruity-floral style that fits spring and summer daytime wear, casual outings, and feminine everyday use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mayar-ladies-edp.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Mayar-84309.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/mayar-eau-de-parfum",
        image_sources=[
            "https://cdn.shopify.com/s/files/1/0754/4936/8799/files/1_a400747a-6731-4eec-b41c-79b2e209a7fc.png?v=1756361945",
        ],
        official_discrepancy_note="A cached Lattafa USA product result exists for this barcode, but the direct product page did not resolve cleanly during this pass, so notes were anchored to Jomashop, Fragrantica, and Parfumo.",
    ),
    ProductSeed(
        product_id=155,
        barcode="6290360598963",
        brand="Lattafa",
        name="Lattafa Mayar Cherry Intense Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich unisex eau de parfum with bright strawberry sparkle, a jammy cherry-cacao heart, and a warm vanilla patchouli base.",
        top_notes="Strawberry, Bergamot",
        mid_notes="Cherry Jam, Cacao",
        base_notes="Vanilla, Patchouli, Amber",
        scent="Fruity sweet gourmand oriental",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Mayar Cherry Intense, Eau De Parfum, Unisex, 100ml, 3.4 oz, Strawberry, Cherry Jam, Cacao, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Jammy cherry-cacao profile with warm vanilla-patchouli depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community sources lean feminine while the retailer listing stays broader, so the safest fit is a sweet gourmand cherry profile that wears best in cooler weather, evenings, and social settings.",
        source_official_url="https://www.lattafa-usa.com/products/mayar-cherry-intense",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-mayar-cherry-intense-edp-spray-3-4-oz-fragrances-6290360598963.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Mayar-Cherry-Intense-99872.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/mayar-cherry-intense-eau-de-parfum",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_a400747a-6731-4eec-b41c-79b2e209a7fc.png?v=1756361945",
            "https://www.lattafa-usa.com/cdn/shop/files/2_454dc454-82b3-46f6-a0cf-92966fbc8f28.png?v=1756361946&width=810",
        ],
        official_discrepancy_note="Parfumo classifies this release as women's, while the current Jomashop listing and marketplace positioning support a broader unisex presentation.",
    ),
    ProductSeed(
        product_id=148,
        barcode="6290360593159",
        brand="Lattafa",
        name="Lattafa Musamam White Intense Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy unisex eau de parfum with citrus-spice brightness, a tropical coconut floral heart, and a smooth sandalwood-benzoin base.",
        top_notes="Spices, Bergamot, Orange",
        mid_notes="Coconut, Ylang-Ylang, Ambroxan, Mahonial",
        base_notes="Sandalwood, Musk, Benzoin",
        scent="Creamy spicy woody coconut",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Musamam White Intense, Eau De Parfum, Unisex, 100ml, 3.4 oz, Coconut, Ylang-Ylang, Sandalwood, Benzoin",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy coconut-spice profile with woody resinous depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo. Source-backed wear guidance places it in the creamy spicy-woody lane, working especially well in cooler weather or evening wear while still staying smooth rather than loud.",
        source_official_url="https://www.lattafa-usa.com/products/musamam-white-intense",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Musamam-White-Intense-85087.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/musamam-white-intense",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Musamam-White-1.png?v=1747416325",
        ],
    ),
    ProductSeed(
        product_id=170,
        barcode="6290360598871",
        brand="Lattafa",
        name="Lattafa Nasmaat Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A juicy unisex eau de parfum with tropical fruit on top, a bright floral heart, and a creamy caramel-vanilla woody base.",
        top_notes="Blackcurrant, Pineapple, Apricot",
        mid_notes="Orange Blossom, Cyclamen, Magnolia, Jasmine, Rose",
        base_notes="Sandalwood, Cashmeran, Vanilla, Caramel",
        scent="Fruity floral sweet woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Nasmaat, Eau De Parfum, Unisex, 100ml, 3.4 oz, Blackcurrant, Pineapple, Orange Blossom, Caramel",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Juicy fruity-floral style with creamy caramel vanilla warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to an approachable sweet fruity-floral profile that fits everyday casual wear and social settings better than formal or austere use.",
        source_official_url="https://www.lattafa-usa.com/products/nasmaat",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-nasmaat-edp-spray-3-4-oz-fragrances-6290360598871.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Nasmaat-130457.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/nasmaat",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Nasmaat.png?v=1760130127",
            "https://www.lattafa-usa.com/cdn/shop/files/Nasmaat_2.png?v=1760130127&width=810",
        ],
    ),
    ProductSeed(
        product_id=64,
        barcode="6291108738276",
        brand="Lattafa",
        name="Lattafa Nebras Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A sweet unisex eau de parfum with berry-citrus sparkle, a cacao-vanilla floral heart, and a warm amber musk base.",
        top_notes="Red Berries, Mandarin Orange",
        mid_notes="Vanilla, Cacao, Rose",
        base_notes="Sugar, Tonka Bean, Amber, Musk",
        scent="Vanilla sweet cacao warm spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Nebras, Eau De Parfum, Unisex, 100ml, 3.4 oz, Red Berries, Vanilla, Cacao, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet vanilla-cacao profile with amber musk warmth.",
        ],
        similar_to="Billie Eilish Eilish",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most consistently points toward the Eilish lane, with source-backed use leaning to cozy cooler-weather wear, nights out, and sweet gourmand lovers.",
        source_official_url="https://www.lattafa-usa.com/products/nebras",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-pride-nebras-edp-3-4-oz-fragrances-6291108738276.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Nebras-78560.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/lattafa-pride/nebras",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_fec4173e-be08-4afa-9cf2-4e9e2285d48f.png?v=1747550775",
        ],
        official_discrepancy_note="Some marketplace rows treated Nebras as women's, but the major fragrance references and current retailer listing support a broader unisex positioning.",
    ),
    ProductSeed(
        product_id=151,
        barcode="6290362348054",
        brand="Lattafa",
        name="Lattafa Nebras Elixir Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy unisex eau de parfum with airy milk-candy sweetness, soft heliotrope in the heart, and a smooth vanilla-musk base.",
        top_notes="Milk Candy, Whipped Cream",
        mid_notes="Sugar Cane, Heliotrope",
        base_notes="Vanilla, Ambroxan, Musk",
        scent="Vanilla sweet powdery musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Nebras Elixir, Eau De Parfum, Unisex, 100ml, 3.4 oz, Milk Candy, Whipped Cream, Heliotrope, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy airy vanilla profile with milky candy softness.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to a soft cozy gourmand style that works best for comfort wear, layering, and sweet casual use rather than bold projection-heavy wear.",
        source_official_url="https://www.lattafa-usa.com/products/nebras-elixir",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-nebras-elixir-edp-spray-3-4-oz-fragrances-6290362348054.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Nebras-Elixir-113906.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/lattafa-pride/nebras-elixir",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/IMG-1145.png?v=1755360827",
            "https://www.lattafa-usa.com/cdn/shop/files/IMG-1146.png?v=1755360830&width=810",
        ],
    ),
    ProductSeed(
        product_id=46,
        barcode="6290362341321",
        brand="Lattafa",
        name="Lattafa Opulent Dubai Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A vivid unisex eau de parfum with sparkling mango citrus up top, a fresh floral-woody heart, and a smooth ambergris-woody base.",
        top_notes="Mango, Ginger, Grapefruit, Lemon",
        mid_notes="Cedarwood, Jasmine, Violet",
        base_notes="Ambergris, Benzoin, Oakmoss, Woody Notes",
        scent="Fruity sweet fresh woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Opulent Dubai, Eau De Parfum, Unisex, 100ml, 3.4 oz, Mango, Grapefruit, Jasmine, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Bright mango-citrus profile with woody ambergris depth.",
        ],
        similar_to="Stephane Humbert Lucas God of Fire",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most often points toward the God of Fire lane, with source-backed wear guidance favoring warm-weather daytime, vacations, and fruity statement wear.",
        source_official_url="https://www.lattafa-usa.com/products/opulent-dubai",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-opulent-dubai-edp-spray-3-4-oz-fragrances-6290362341321.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Opulent-Dubai-105609.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/opulent-dubai",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_7d5801be-0a5e-4ac4-bffc-3bee4a3c7a6b.png?v=1756143162",
        ],
    ),
    ProductSeed(
        product_id=145,
        barcode="6290360598796",
        brand="Lattafa",
        name="Lattafa Petra Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A warm unisex eau de parfum with boozy plum up top, creamy tuberose and coconut in the heart, and a sweet musky praline-vanilla base.",
        top_notes="Rum, Plum",
        mid_notes="Tuberose, Coconut",
        base_notes="Vanilla, Musk, Praline",
        scent="Sweet creamy fruity floral",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Petra, Eau De Parfum, Unisex, 100ml, 3.4 oz, Rum, Plum, Tuberose, Praline",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Boozy plum opening with creamy tuberose-coconut and sweet praline warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance leans toward sweeter statement wear, evenings, and cooler weather or sunset-style summer wear rather than bright daytime freshness.",
        source_official_url="https://www.lattafa-usa.com/products/petra",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-petra-edp-spray-3-4-oz-fragrances-6290360598796.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Petra-107089.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/petra",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_6e8e4461-9e8c-4346-b7aa-87769f89fad6.png?v=1749465674",
        ],
        official_discrepancy_note="Parfumo currently leans more feminine in its profile language, while Fragrantica and retailer listings keep Petra broader.",
    ),
    ProductSeed(
        product_id=53,
        barcode="6290360592206",
        brand="Lattafa",
        name="Lattafa Art of Universe Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright unisex eau de parfum with sparkling citrus-mint energy, a juicy pear-floral heart, and a clean woody amber base.",
        top_notes="Mandarin Orange, Bergamot, Ginger, Mint",
        mid_notes="Pear, Orange Blossom",
        base_notes="Musk, Amber, Cedarwood",
        scent="Fruity fresh sweet citrus",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Art of Universe, Eau De Parfum, Unisex, 100ml, 3.4 oz, Mandarin Orange, Ginger, Pear, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Sparkling citrus-fruity profile with a clean woody amber base.",
        ],
        similar_to="Ex Nihilo Blue Talisman",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most often points toward the Blue Talisman lane, with source-backed wear guidance favoring fresh signature wear, spring/summer use, and bright social or daytime settings.",
        source_official_url="https://www.lattafa-usa.com/products/art-of-universe",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-art-of-universe-edp-spray-3-4-oz-fragrances-6290360592206.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Art-Of-Universe-101314.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/lattafa-pride/art-of-universe",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_95e6ea50-ba7d-4fde-8082-c749525eb33a.png?v=1747555499",
        ],
        official_discrepancy_note="Parfumo currently labels Art of Universe as men's, while Jomashop and broader marketplace positioning support unisex.",
    ),
    ProductSeed(
        product_id=50,
        barcode="6290360592909",
        brand="Lattafa",
        name="Lattafa Vintage Radio Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy unisex eau de parfum with aromatic lavender-sage brightness, a smooth plum palo santo heart, and a woody amber base.",
        top_notes="Lavender, Sage, Bergamot",
        mid_notes="Plum, Palo Santo, Black Pepper",
        base_notes="Amberwood, Sandalwood",
        scent="Sweet creamy fruity woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Vintage Radio, Eau De Parfum, Unisex, 100ml, 3.4 oz, Lavender, Plum, Palo Santo, Sandalwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy plum-woody style with aromatic opening and smooth sandalwood base.",
        ],
        similar_to="Initio Paragon",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparison most consistently points toward the Paragon lane, with source-backed wear guidance favoring cooler weather, evening use, and people who enjoy creamy plum-woody scents.",
        source_official_url="https://www.lattafa-usa.com/products/vintage-radio",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-pride-vintage-radio-edp-spray-3-4-oz-fragrances-6290360592909.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Vintage-Radio-89454.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/lattafa-pride/vintage-radio",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_e79a03d9-b9c0-4660-b6eb-3a1ff39f02f0.png?v=1749326347",
        ],
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
