#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_eleventh10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=146,
        barcode="6290360598789",
        brand="Lattafa",
        name="Lattafa Victoria Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright unisex eau de parfum with lemon-meringue sweetness, airy neroli in the heart, and a soft vanilla finish.",
        top_notes="Lemon Meringue Pie",
        mid_notes="Neroli",
        base_notes="Vanilla",
        scent="Citrus sweet gourmand vanilla",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Victoria, Eau De Parfum, Unisex, 100ml, 3.4 oz, Lemon Meringue Pie, Neroli, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Lemon dessert opening with neroli brightness and creamy vanilla drydown.",
        ],
        similar_to="Dolce & Gabbana Devotion",
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo. Community comparison most often points toward the Devotion lane, with source-backed wear guidance favoring spring and summer daytime wear, cheerful casual use, and gourmand citrus lovers.",
        source_official_url="https://www.lattafa-usa.com/products/victoria",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Victoria-102906.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/victoria",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Victoria-1_5951ef1c-61de-4bd1-9d5f-1d2b3d1c18cc.png?v=1747417320",
            "https://fimgs.net/mdimg/perfume/375x500.102906.jpg",
        ],
        official_discrepancy_note="Lattafa USA and Fragrantica position Victoria for women and men, while Parfumo currently frames it more narrowly as women's.",
    ),
    ProductSeed(
        product_id=35,
        barcode="6291108730515",
        brand="Lattafa",
        name="Lattafa Yara Eau de Parfum Spray 100ml (3.38 oz) Women Perfume",
        gender="Women",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A soft women's eau de parfum with creamy orchid and tangerine on top, tropical gourmand warmth in the heart, and a musky vanilla sandalwood base.",
        top_notes="Orchid, Heliotrope, Tangerine",
        mid_notes="Gourmand Accord, Tropical Fruits",
        base_notes="Vanilla, Musk, Sandalwood",
        scent="Sweet creamy fruity vanilla",
        feature="eau de parfum spray; women; 100ml / 3.38 oz",
        keywords="Lattafa, Yara, Eau De Parfum, Women, 100ml, 3.38 oz, Orchid, Heliotrope, Tropical Fruits, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.38 oz bottle size.",
            "Creamy sweet-fruity profile with soft vanilla sandalwood finish.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to an easy sweet feminine scent that works especially well for everyday wear, warm weather, and soft playful styling.",
        source_official_url="https://www.lattafa-usa.com/products/yara",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-yara-edp-spray-3-38-oz-fragrances-6291108730515.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Yara-76880.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/yara",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_7682153c-2dce-4b60-a9e6-20557f8502cf.png?v=1747500015",
            "https://fimgs.net/mdimg/perfume/375x500.76880.jpg",
        ],
    ),
    ProductSeed(
        product_id=43,
        barcode="6290360599168",
        brand="Lattafa",
        name="Lattafa Yara Candy Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A playful women's eau de parfum with juicy blackcurrant and green tangerine, fizzy strawberry candy in the heart, and sweet vanilla musk in the base.",
        top_notes="Black Currant, Green Tangerine",
        mid_notes="Strawberry Fizz Candy, Gardenia",
        base_notes="Vanilla, Musk, Amber, Sandalwood",
        scent="Sweet fruity candy creamy",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Yara Candy, Eau De Parfum, Women, 100ml, 3.4 oz, Black Currant, Strawberry Candy, Gardenia, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Candy-fruity style with creamy vanilla musk drydown.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. The source-backed fit is cheerful sweet casual wear, spring and summer use, and buyers who like playful candy-fruity scents.",
        source_official_url="https://www.lattafa-usa.com/products/yara-candy",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-yara-candy-edp-spray-3-4-oz-fragrances-6290360599168.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Yara-Candy-95752.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/yara-candy-eau-de-parfum",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Yara-Candy-1_86796aee-3226-4653-ba72-dd51d747c7f4.png?v=1747416617",
            "https://fimgs.net/mdimg/perfume/375x500.95752.jpg",
        ],
    ),
    ProductSeed(
        product_id=63,
        barcode="6290362346531",
        brand="Lattafa",
        name="Lattafa Yara Elixir Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A richer women's eau de parfum with strawberry s'mores and black currant on top, jasmine and orange flower in the heart, and creamy caramel vanilla in the base.",
        top_notes="Strawberry S'mores, Black Currant",
        mid_notes="Jasmine, Orange Flower",
        base_notes="Vanilla, Caramel, Amber, Musk",
        scent="Sweet creamy fruity gourmand",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Yara Elixir, Eau De Parfum, Women, 100ml, 3.4 oz, Strawberry S'mores, Black Currant, Caramel, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy gourmand berry profile with caramelized vanilla warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to sweeter evening or cooler-weather use, while still staying feminine and playful rather than dark or smoky.",
        source_official_url="https://www.lattafa-usa.com/products/yara-elixir",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-yara-elixir-edp-spray-3-4-oz-fragrances-6290362346531.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Yara-Elixir-117615.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/yara-elixir",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/YaraElixirBottle.png?v=1760805808",
            "https://fimgs.net/mdimg/perfume/375x500.117615.jpg",
        ],
    ),
    ProductSeed(
        product_id=67,
        barcode="6290360591421",
        brand="Lattafa",
        name="Lattafa Yara Moi Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy women's eau de parfum with peach and jasmine up top, caramel and amber in the heart, and a soft patchouli-sandalwood base.",
        top_notes="Jasmine, Peach",
        mid_notes="Caramel, Amber",
        base_notes="Patchouli, Sandalwood",
        scent="Creamy floral sweet woody",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Yara Moi, Eau De Parfum, Women, 100ml, 3.4 oz, Peach, Jasmine, Caramel, Sandalwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy peach-floral style with caramel warmth and soft patchouli woods.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance leans toward cozy feminine daily wear, cooler weather, and buyers who like creamy floral-gourmand styles.",
        source_official_url="https://www.lattafa-usa.com/products/yara-moi",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-yara-moi-edp-spray-3-4-oz-fragrances-6290360591421.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Yara-Moi-80722.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/yara-moi-eau-de-parfum",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Yara-Moi-1_81ec2a74-066f-45ef-b35a-465dfda22eac.png?v=1747422182",
            "https://fimgs.net/mdimg/perfume/375x500.80722.jpg",
        ],
    ),
    ProductSeed(
        product_id=162,
        barcode="6290362345749",
        brand="Lattafa",
        name="Lattafa Yara Mini Collection 4 x 5ml EDP Gift Set Women Perfume",
        gender="Women",
        size_oz=0.68,
        size_ml=20,
        volume_oz=0.68,
        volume_ml=20,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A women's mini gift set featuring four Yara eau de parfums in travel-friendly 5ml bottles: Yara, Yara Candy, Yara Tous, and Yara Moi.",
        top_notes="Varies by included fragrance set",
        mid_notes="Includes Yara, Yara Candy, Yara Tous, and Yara Moi",
        base_notes="See included component fragrances for individual note pyramids",
        scent="Mixed sweet fruity floral gourmand collection",
        feature="gift set; women; 4 x 5ml / total 20ml",
        keywords="Lattafa, Yara Mini Collection, Gift Set, Women, 4 x 5ml, Yara, Yara Candy, Yara Tous, Yara Moi",
        highlights=[
            "Gift set with four Yara minis.",
            "Includes Yara, Yara Candy, Yara Tous, and Yara Moi.",
            "4 x 5 mL / total 20 mL travel-friendly format.",
            "Great sampler or gifting option for the Yara line.",
        ],
        similar_to=None,
        verified_note="Verified from the official Lattafa USA set page and barcode-matched retailer listings. This was saved as a multi-fragrance gift set rather than forcing a single note pyramid onto four different perfumes.",
        source_official_url="https://www.lattafa-usa.com/products/yara-collection-set",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/IMG-0323.png?v=1753249372",
        ],
        official_discrepancy_note="Public retailer listings disagree between 4 x 5ml and 4 x 25ml wording, but the current Lattafa USA page explicitly titles this set as 4 x 5ml, so that official size was used.",
    ),
    ProductSeed(
        product_id=52,
        barcode="6290360594552",
        brand="Lattafa",
        name="Lattafa Yara Tous Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A tropical women's eau de parfum with mango, coconut, and passionfruit on top, white florals in the heart, and a creamy vanilla musk base.",
        top_notes="Mango, Coconut, Passionfruit",
        mid_notes="Jasmine, Heliotrope, Orange Blossom",
        base_notes="Vanilla, Musk, Cashmeran",
        scent="Tropical sweet fruity floral",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Yara Tous, Eau De Parfum, Women, 100ml, 3.4 oz, Mango, Coconut, Passionfruit, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Tropical fruit-and-coconut profile with creamy vanilla softness.",
        ],
        similar_to="Rabanne Fame",
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo, with Jomashop and marketplace support. Community comparison often points toward the Fame lane, and the source-backed wear fit is summer daytime, vacations, and tropical sweet-fresh use.",
        source_official_url="https://www.lattafa-usa.com/products/yara-tous",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Yara-Tous-83320.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/yara-tous",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_5fe75433-0467-4d06-87e9-d9e81ac2da00.png?v=1749487600",
            "https://fimgs.net/mdimg/perfume/375x500.83320.jpg",
        ],
    ),
    ProductSeed(
        product_id=189,
        barcode="6290360598895",
        brand="Lattafa",
        name="Lattafa Layaan Eau de Parfum Spray 75ml (2.53 oz) Women Perfume",
        gender="Women",
        size_oz=2.53,
        size_ml=75,
        volume_oz=2.53,
        volume_ml=75,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A luminous women's eau de parfum with green pear and mandarin on top, white florals through the heart, and a clean cedar-musk base.",
        top_notes="Green Pear, Mandarin",
        mid_notes="Gardenia, Jasmine, Lily of the Valley",
        base_notes="Cedarwood, Musk",
        scent="Fruity floral fresh woody",
        feature="eau de parfum spray; women; 75ml / 2.53 oz",
        keywords="Lattafa, Layaan, Eau De Parfum, Women, 75ml, 2.53 oz, Green Pear, Mandarin, Gardenia, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "75 mL / 2.53 oz bottle size.",
            "Fresh pear-floral profile with clean musky cedar finish.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to a fresh pretty feminine style that suits daily wear, spring and summer, and clean fruity-floral preferences.",
        source_official_url="https://www.lattafa-usa.com/products/layaan",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-layaan-edp-spray-2-53-oz-fragrances-6290360598895.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Layaan-117123.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/layaan",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_56ca40c3-8a27-4c18-93a1-3e43627efcc9.png?v=1759429729",
            "https://fimgs.net/mdimg/perfume/375x500.117123.jpg",
        ],
    ),
    ProductSeed(
        product_id=198,
        barcode="6290360375694",
        brand="French Avenue",
        name="French Avenue Liquid Brun Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Fragrance World Trading LLC",
        description_intro="A warm unisex eau de parfum with cinnamon-cardamom spice up top, bourbon vanilla and elemi in the heart, and a sweet praline-ambery woody base.",
        top_notes="Orange Blossom, Cardamom, Cinnamon, Bergamot",
        mid_notes="Bourbon Vanilla, Elemi Resin",
        base_notes="Praline, Musk, Ambroxan, Guaiac Wood",
        scent="Sweet gourmand vanilla spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="French Avenue, Liquid Brun, Eau De Parfum, Unisex, 100ml, 3.4 oz, Cinnamon, Bourbon Vanilla, Praline, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from French Avenue.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet spicy vanilla profile with praline and ambery woods.",
        ],
        similar_to="Parfums de Marly Althair",
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop coverage. Community comparison overwhelmingly points toward the Althair lane, and the source-backed wear fit is cooler weather, evenings, and gourmand-leaning sweet-spicy use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/fragrance-world-mens-french-avenue-liquid-brun-edp-spray-3-4-oz-fragrances-6290360375694-event.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/French-Avenue/Liquid-Brun-94713.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/french-avenue/liquid-brun",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.94713.jpg",
        ],
        official_discrepancy_note="Brand presentation varies between French Avenue and Fragrance World reseller copy. The saved record uses French Avenue as the fragrance line and Fragrance World Trading LLC as manufacturer, matching Parfumo and broader market positioning.",
    ),
    ProductSeed(
        product_id=173,
        barcode="6290362341116",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Journey Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich unisex eau de parfum in Maison Alhambra's Luxe collection with a sweet-creamy character and darker fruity-oud impressions in user-supported descriptions.",
        top_notes="Public note listings conflict across sources",
        mid_notes="Public note listings conflict across sources",
        base_notes="Public note listings conflict across sources",
        scent="Sweet creamy woody fruity",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Journey, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Saved carefully with conflict notes instead of forcing an unreliable public pyramid.",
        ],
        similar_to=None,
        verified_note="Verified from Jomashop, Fragrantica, and Parfumo at the product identity level. Public note pyramids are inconsistent and openly disputed, so this record preserves the confirmed product facts while marking the note structure as conflicted rather than inventing a clean pyramid.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-ladies-luxe-journey-edp-spray-3-4-oz-fragrances-6290362341116.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Luxe-Journey-107582.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/maison-alhambra/luxe-journey",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.107582.jpg",
        ],
        official_discrepancy_note="Fragrantica lists a full note pyramid, but community comments there explicitly state those notes appear to belong to another Luxe release. Parfumo only confirms the product identity and character, so this record keeps the identity enrichment while marking the note pyramid as unresolved.",
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
