#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from server.company_db import get_product, utc_now
from server.postgres_cutover import POSTGRES_SIDECAR_SCHEMA, _pg_connect
from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    build_gallery,
    category_name_for_gender,
    description_html,
    description_text,
    volume_text,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_fifth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=226,
        barcode="6290362348108",
        brand="Lattafa Pride",
        name="Lattafa Pride Mini Gift Set 5 x 20ml (Affection / Tharwah Gold / 1505 / Breeze / Shaheen Gold) 100ml (3.38 oz) Unisex Fragrance Set",
        gender="Unisex",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A curated Lattafa Pride travel gift set featuring five 20 mL fragrances for rotating between sweet, fresh, woody, and more dressed-up scent moods.",
        top_notes="Varies by included fragrance in the set",
        mid_notes="Varies by included fragrance in the set",
        base_notes="Varies by included fragrance in the set",
        scent="Mixed fragrance set",
        feature="gift set; unisex; 5 x 20ml / 100ml total",
        keywords="Lattafa Pride, Mini Gift Set, Affection, Tharwah Gold, 1505, Breeze, Shaheen Gold, 5 x 20ml, unisex fragrance set",
        highlights=[
            "Gift set with five 20 mL fragrances.",
            "100 mL / 3.38 oz total volume.",
            "Includes Affection, Tharwah Gold, 1505, Breeze, and Shaheen Gold.",
            "Travel-friendly discovery and gifting format.",
        ],
        similar_to=None,
        verified_note="Verified from Jomashop retailer data, DM product data, and wholesale listing trails tied to this barcode. This is a mixed mini set rather than one single fragrance profile, so the saved notes intentionally describe the set contents instead of inventing one pyramid.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mini-set-gift-set-fragrances-6290362348108.html",
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mini-set-gift-set-fragrances-6290362348108.jpg?width=800&height=800",
            "https://cdn2.jomashop.com/media/catalog/product/cache/0ee3019724ce73007b606b54ba535a23/l/a/lattafa-mini-set-gift-set-fragrances-6290362348108.jpg?width=546&height=546",
        ],
        official_discrepancy_note="Multiple retailer trails agree on the exact five-piece contents for this barcode, but there is no exact official product page tied to the set, so the record is intentionally saved as a fragrance set rather than a single perfume profile.",
    ),
    ProductSeed(
        product_id=227,
        barcode="6290362348078",
        brand="Lattafa Pride",
        name="Lattafa Pride Mini Gift Set 5 x 20ml (Artisan Ethnique / Natural Oud / Tharwah Silver / Eternal Oud / Shuyukh Gold) 100ml (3.38 oz) Unisex Fragrance Set",
        gender="Unisex",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A curated Lattafa Pride mini gift set with five 20 mL fragrances spanning woody, oud, and polished everyday wear options in one travel-ready box.",
        top_notes="Varies by included fragrance in the set",
        mid_notes="Varies by included fragrance in the set",
        base_notes="Varies by included fragrance in the set",
        scent="Mixed fragrance set",
        feature="gift set; unisex; 5 x 20ml / 100ml total",
        keywords="Lattafa Pride, Mini Gift Set, Artisan Ethnique, Natural Oud, Tharwah Silver, Eternal Oud, Shuyukh Gold, 5 x 20ml, unisex fragrance set",
        highlights=[
            "Gift set with five 20 mL fragrances.",
            "100 mL / 3.38 oz total volume.",
            "Includes Artisan Ethnique, Natural Oud, Tharwah Silver, Eternal Oud, and Shuyukh Gold.",
            "Travel-friendly discovery and gifting format.",
        ],
        similar_to=None,
        verified_note="Verified from Jomashop retailer data and secondary retailer mirrors tied to this barcode. This is a mixed mini set, so the record stays focused on exact set contents instead of inventing a single top/mid/base pyramid.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mini-set-gift-set-fragrances-6290362348078.html",
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mini-set-gift-set-fragrances-6290362348078.jpg?width=800&height=800",
            "https://cdn2.jomashop.com/media/catalog/product/cache/0ee3019724ce73007b606b54ba535a23/l/a/lattafa-mini-set-gift-set-fragrances-6290362348078.jpg?width=546&height=546",
        ],
        official_discrepancy_note="Retailer trails consistently list this barcode as a five-piece Lattafa Pride mini set with Artisan Ethnique, Natural Oud, Tharwah Silver, Eternal Oud, and Shuyukh Gold, but no exact official barcode page was found.",
    ),
    ProductSeed(
        product_id=40,
        barcode="6291108735411",
        brand="Lattafa",
        name="Lattafa Asad Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A bold spicy-amber men's fragrance with tobacco and black pepper up top, darker coffee-iris depth through the heart, and a warm resinous vanilla base.",
        top_notes="Black Pepper, Pineapple, Tobacco",
        mid_notes="Coffee, Patchouli, Iris",
        base_notes="Amber, Vanilla, Dry Woods, Benzoin, Labdanum",
        scent="Spicy sweet woody amber",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Asad, Eau De Parfum, Men, 100ml, 3.4 oz, Black Pepper, Tobacco, Coffee, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Spicy-sweet amber profile with coffee, tobacco, and vanilla depth.",
        ],
        similar_to="Dior Sauvage Elixir",
        verified_note="Verified from Jomashop product data, Hinta's mirrored spec sheet tied to the official product link, Fragrantica, and Parfumo. Source-backed wear guidance consistently puts Asad in the stronger evening, cooler-weather, statement-fragrance lane rather than an easy hot-weather freshie.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-asad-edp-spray-3-4-oz-fragrances-6291108735411.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-72821.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/asad",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-asad-edp-spray-34-oz-fragrances-6291108735411.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.72821.jpg",
        ],
    ),
    ProductSeed(
        product_id=45,
        barcode="6291107458328",
        brand="Lattafa",
        name="Lattafa Bade'e Al Oud Oud for Glory Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A dark warm-spicy oud fragrance with saffron and lavender up top, patchouli through the heart, and a musky woody oud finish.",
        top_notes="Saffron, Nutmeg, Lavender",
        mid_notes="Agarwood (Oud), Patchouli",
        base_notes="Agarwood (Oud), Patchouli, Musk",
        scent="Oud warm spicy woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Bade'e Al Oud Oud for Glory, Eau De Parfum, Unisex, 100ml, 3.4 oz, Saffron, Oud, Patchouli, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Dark oud-forward profile with saffron, patchouli, and musk.",
        ],
        similar_to="Initio Oud for Greatness",
        verified_note="Verified from Lattafa USA, Fragrantica, Parfumo, and Jomashop retailer support. This is consistently described as a strong darker oud profile best suited to cooler weather, evenings, and anyone specifically looking for a bold statement scent.",
        source_official_url="https://lattafa-usa.com/products/lattafa-badee-al-oud-oud-for-glory-eau-de-parfum-for-everyone",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Bade-e-Al-Oud-Oud-for-Glory-64948.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/bade-e-al-oud-oud-for-glory",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.64948.jpg",
        ],
        official_discrepancy_note="The exact Jomashop product page was not available by direct URL, but the official Lattafa USA page and both fragrance databases align on the note pyramid and unisex positioning.",
    ),
    ProductSeed(
        product_id=259,
        barcode="6290360593173",
        brand="Lattafa",
        name="Lattafa Al Nashama Caprice Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A vibrant aromatic-spicy fragrance with bright citrus and cardamom in the opening, a minty lavender-geranium heart, and a dry woody amber-vetiver base.",
        top_notes="Cardamom, Ginger, Bergamot, Lemon",
        mid_notes="Lavender, Geranium, Mint",
        base_notes="Amber, Cedarwood, Patchouli, Vetiver",
        scent="Sweet spicy woody fresh",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Al Nashama Caprice, Eau De Parfum, Unisex, 100ml, 3.4 oz, Cardamom, Ginger, Lavender, Vetiver",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh spicy-aromatic profile with cardamom, mint, and amber wood depth.",
        ],
        similar_to="Yves Saint Laurent La Nuit de L'Homme Bleu Électrique",
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop retailer data. Source-backed impressions place this one in the polished aromatic evening/date-night lane with enough versatility for everyday wear when you like a fresher spicy style.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-al-nashama-caprice-edp-3-4-oz-fragrances-6290360593173.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Al-Nashama-Caprice-89764.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/al-nashama-caprice",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-al-nashama-caprice-edp-34-oz-fragrances-6290360593173.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.89764.jpg",
        ],
    ),
    ProductSeed(
        product_id=229,
        barcode="6291106063707",
        brand="Lattafa",
        name="Lattafa Ameer Al Oudh Gift Set 100ml + 50ml Unisex Fragrance Set",
        gender="Unisex",
        size_oz=5.1,
        size_ml=150,
        volume_oz=5.1,
        volume_ml=150,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A two-piece Ameer Al Oudh gift set pairing the fragrance with a matching deodorant spray in a warm woody sweet Middle Eastern style.",
        top_notes="Agarwood (Oud)",
        mid_notes="Woody Notes",
        base_notes="Vanilla, Sugar",
        scent="Woody oud sweet",
        feature="gift set; unisex; 100ml perfume + 50ml deodorant",
        keywords="Lattafa, Ameer Al Oudh, Gift Set, Unisex, 100ml, 50ml, Oud, Woody, Vanilla, Sweet",
        highlights=[
            "Two-piece gift set with 100 mL perfume and 50 mL deodorant spray.",
            "150 mL / 5.1 oz total volume.",
            "Warm woody sweet profile from the Ameer Al Oudh line.",
            "Gift-ready format for fans of richer Middle Eastern scents.",
        ],
        similar_to=None,
        verified_note="Verified from the Lattafa USA gift-set page, the exact Jomashop barcode page, Fragrantica, and retailer mirrors tied to this barcode. Sources conflict on the exact pyramid, so the saved note profile follows barcode-matched gift-set retailer listings rather than forcing the separate Ameer Al Oudh loose-bottle data.",
        source_official_url="https://lattafa-usa.com/products/lattafa-ameer-al-oudh-gift-set-for-everyone",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-ameer-al-oudh-edp-spray-3-4-oz-fragrances-6291106063707.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ameer-Al-Oudh-25826.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/Ameer_Al_Oudh",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-ameer-al-oudh-edp-spray-34-oz-fragrances-6291106063707.jpg?width=800&height=800",
        ],
        official_discrepancy_note="The official gift-set page describes the scent family but not a full exact pyramid, while Fragrantica and retailer mirrors disagree on the note structure. The saved top/mid/base follows barcode-matched set listings and keeps the discrepancy documented.",
    ),
    ProductSeed(
        product_id=61,
        barcode="6291107454412",
        brand="Lattafa",
        name="Lattafa Ana Abiyedh Rouge Eau de Parfum Spray 60ml (2.03 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=2.03,
        size_ml=60,
        volume_oz=2.03,
        volume_ml=60,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A sweet airy amber fragrance with bright pear-citrus up top, caramel through the heart, and a musky ambergris finish.",
        top_notes="Nashi Pear, Kumquat, Bergamot",
        mid_notes="Caramel, Geranium",
        base_notes="Ambergris, Musk, Oakmoss",
        scent="Sweet fruity amber musky",
        feature="eau de parfum spray; unisex; 60ml / 2.03 oz",
        keywords="Lattafa, Ana Abiyedh Rouge, Eau De Parfum, Unisex, 60ml, 2.03 oz, Pear, Kumquat, Caramel, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Shared-wear fragrance from Lattafa.",
            "60 mL / 2.03 oz bottle size.",
            "Sweet airy amber profile with caramel and musky depth.",
        ],
        similar_to="Maison Francis Kurkdjian Baccarat Rouge 540",
        verified_note="Verified from Jomashop, Hinta's mirrored spec sheet tied to the official product link, Fragrantica, and Parfumo. Source-backed impressions place it in the airy sweet-amber BR540-inspired lane with strongest use cases around cooler weather, evenings, and overspray-conscious wear.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-ana-abiyedh-rouge-edp-spray-2-03-oz-fragrances-6291107454412.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ana-Abiyedh-Rouge-63062.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/ana-abiyedh-rouge",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-ana-abiyedh-rouge-edp-spray-203-oz-fragrances-6291107454412.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.63062.jpg",
        ],
        official_discrepancy_note="Retailer and community sources split between unisex and women-leaning positioning; the saved record keeps it unisex because the product is broadly marketed that way in retailer data and the scent profile is shared-wear in practice.",
    ),
    ProductSeed(
        product_id=152,
        barcode="6290362341826",
        brand="Lattafa",
        name="Lattafa Ana Abiyedh Coral Eau de Parfum Spray 60ml (2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=2.0,
        size_ml=60,
        volume_oz=2.0,
        volume_ml=60,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A juicy sweet-fruity fragrance with watermelon and peach up top, soft white florals and coconut through the heart, and a musky vanilla-amber base.",
        top_notes="Watermelon, Peach, Orange",
        mid_notes="White Blossoms, Coconut",
        base_notes="Musk, Amber, Vanilla",
        scent="Sweet fruity fresh floral",
        feature="eau de parfum spray; unisex; 60ml / 2 oz",
        keywords="Lattafa, Ana Abiyedh Coral, Eau De Parfum, Unisex, 60ml, 2 oz, Watermelon, Peach, Coconut, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "60 mL / 2 oz bottle size.",
            "Juicy fruity profile with watermelon, coconut, and musky vanilla drydown.",
        ],
        similar_to="Room 1015 Wavechild",
        verified_note="Verified from Fragrantica, Parfumo, and barcode-matched retailer trails. Source-backed community comparisons repeatedly place this in the fun summer fruity lane, especially for vacation wear, daytime casual use, and easy warm-weather rotation.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ana-Abiyedh-Coral-103256.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/ana-abiyedh-coral",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.103256.jpg",
        ],
        official_discrepancy_note="The exact Jomashop product appeared only through filtered collection results rather than a clean direct product page, so the saved notes rely on the Fragrantica and Parfumo exact-match fragrance pages for this barcode line.",
    ),
    ProductSeed(
        product_id=39,
        barcode="6290360598338",
        brand="Lattafa",
        name="Lattafa Angham Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A sweet creamy gourmand fragrance with spicy mandarin sparkle up top, praline-cacao lavender through the heart, and a warm vanilla-musky base.",
        top_notes="Mandarin Orange, Ginger, Pink Pepper",
        mid_notes="Praline, Lavender, Cacao, Jasmine",
        base_notes="Musk, Amber, Vanilla",
        scent="Sweet floral creamy gourmand",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Angham, Eau De Parfum, Unisex, 100ml, 3.4 oz, Mandarin Orange, Praline, Cacao, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Shared-wear fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet creamy gourmand profile with praline, cacao, and vanilla.",
        ],
        similar_to="Burberry Goddess",
        verified_note="Verified from Lattafa USA, Fragrantica, Jomashop retailer data, and Parfumo. Source-backed impressions consistently place Angham in the sweeter cooler-weather, cozy evening, and dressed-up casual lane rather than as a sharp fresh fragrance.",
        source_official_url="https://lattafa-usa.com/products/lattafa-angham-eau-de-parfum-for-everyone",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-angham-edp-spray-3-4-oz-fragrances-6290360598338.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Angham-96768.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/angham",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-angham-edp-spray-34-oz-fragrances-6290360598338.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.96768.jpg",
        ],
        official_discrepancy_note="Lattafa USA markets Angham 'for everyone' while Parfumo currently frames it as women-leaning. The saved record keeps it unisex because the official barcode page and retailer positioning are broader.",
    ),
    ProductSeed(
        product_id=48,
        barcode="6290362340362",
        brand="Lattafa",
        name="Lattafa Asad Bourbon Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A warm sweet-spicy fragrance with pink pepper and mirabelle plum up top, cacao and nutmeg through the heart, and a creamy bourbon-vanilla amber base.",
        top_notes="Pink Pepper, Lavender, Mirabelle Plum",
        mid_notes="Cacao, Davana, Nutmeg",
        base_notes="Vetiver, Bourbon Vanilla, Amber",
        scent="Amber spicy sweet woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Asad Bourbon, Eau De Parfum, Unisex, 100ml, 3.4 oz, Pink Pepper, Cacao, Davana, Bourbon Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Shared-wear fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Warm sweet-spicy profile with cacao, vanilla, and amber depth.",
        ],
        similar_to="Azzaro The Most Wanted Parfum",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed impressions put Asad Bourbon in the sweet warm evening and cooler-weather lane, with a more approachable shared-wear profile than the original Asad for many users.",
        source_official_url="https://lattafa-usa.com/products/lattafa-asad-bourbon-eau-de-parfum-for-everyone",
        source_jomashop_url="https://www.jomashop.com/lattafat-mens-asad-bourbon-3-4-oz-fragrances-6290362340362.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-Bourbon-101124.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/asad-bourbon",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-asad-bourbon-edp-spray-34-oz-fragrances-6290362340362.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.101124.jpg",
        ],
        official_discrepancy_note="Lattafa USA presents Asad Bourbon as for everyone, while some retailer pages still place it in men's categories. The saved record follows the exact official product positioning.",
    ),
]


def update_product(seed: ProductSeed) -> dict[str, Any]:
    current = get_product(seed.product_id) or {}
    primary_image, gallery_json = build_gallery(seed, current)
    now = utc_now()
    updates = {
        "name": seed.name,
        "brand": seed.brand,
        "gender": seed.gender,
        "description": description_text(seed),
        "notes": seed.verified_note,
        "note_top": seed.top_notes,
        "note_mid": seed.mid_notes,
        "note_base": seed.base_notes,
        "size_oz": seed.size_oz,
        "size_ml": seed.size_ml,
        "volume_oz": seed.volume_oz,
        "volume_ml": seed.volume_ml,
        "media_url": primary_image,
        "image_gallery_urls": gallery_json,
        "notes_verified": 1,
        "notes_verified_at": now,
        "similar_to": seed.similar_to,
        "dupe_inspiration": seed.similar_to,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "tiktok_title": seed.name,
        "tiktok_item_name": seed.name,
        "tiktok_category_name": category_name_for_gender(seed.gender),
        "tiktok_brand": seed.brand,
        "tiktok_manufacturer": seed.manufacturer,
        "tiktok_feature": seed.feature,
        "tiktok_search_keywords": seed.keywords,
        "tiktok_scent": seed.scent,
        "tiktok_product_form": seed.product_form,
        "tiktok_fragrance_concentration": seed.product_form,
        "tiktok_volume": volume_text(seed),
        "tiktok_description": description_html(seed),
        "tiktok_highlights": "\n".join(seed.highlights),
        "tiktok_pack_type": "Single item" if seed.product_form != "Gift Set" else "Gift set",
        "tiktok_container_type": "Spray" if seed.product_form != "Gift Set" else "Multi-item set",
        "tiktok_age_group": "Adult",
        "tiktok_region_of_origin": "United Arab Emirates",
        "updated_at": now,
    }
    if seed.ingredients is not None:
        updates["ingredients"] = seed.ingredients
        updates["tiktok_ingredients"] = seed.ingredients
    if seed.package_weight_oz is not None:
        updates["tiktok_package_weight_oz"] = seed.package_weight_oz
    assignments = ", ".join(f"{column} = %s" for column in updates)
    params = list(updates.values()) + [seed.product_id]
    conn = _pg_connect()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"UPDATE {POSTGRES_SIDECAR_SCHEMA}.products SET {assignments} WHERE id = %s",
                    params,
                )
    finally:
        conn.close()
    return {
        "product_id": seed.product_id,
        "barcode": seed.barcode,
        "name": seed.name,
        "gallery_count": 0 if not gallery_json else len(json.loads(gallery_json)),
        "primary_image": primary_image,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "discrepancy_note": seed.official_discrepancy_note,
    }


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
