#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_eighth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=180,
        barcode="6290360590868",
        brand="Asdaaf",
        name="Asdaaf Ameerat Al Arab Prive Rose Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich women's eau de parfum with sweet fruit on top, a full floral-musky heart, and a warm amber-sandalwood base.",
        top_notes="Strawberry, Grapes, Orange",
        mid_notes="Rose, White Musk, Jasmine, Gardenia, Lily, Ylang-Ylang",
        base_notes="Tonka Bean, Amber, Sandalwood",
        scent="Sweet rose musky fruity",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Asdaaf, Ameerat Al Arab Prive Rose, Eau De Parfum, Women, 100ml, 3.4 oz, Strawberry, Rose, White Musk, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Asdaaf by Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet rose-musky profile with warm amber-sandalwood depth.",
        ],
        similar_to="Parfums de Marly Delina / Delina Exclusif",
        verified_note="Verified from Fragrantica and Parfumo, with Lattafa USA catalog support for the exact barcode. Community guidance consistently places it in the Delina-style rose-fruity lane, with stronger wear on cooler days, evenings, and dressier feminine use rather than light office freshness.",
        source_official_url="https://lattafa-usa.com/collections/asdaaf-collection",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Asdaaf/Ameerat-Al-Arab-Prive-Rose-81967.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Asdaaf/ameerat-al-arab-prive-rose-eau-de-parfum",
        image_sources=[
            "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.81967.avif",
        ],
        official_discrepancy_note="Lattafa USA search and catalog support this barcode, but the exact product page did not resolve cleanly during this pass, so the note pyramid was anchored to Fragrantica and Parfumo.",
    ),
    ProductSeed(
        product_id=194,
        barcode="6290362349938",
        brand="Lattafa",
        name="Lattafa Ana Abiyedh Scarlet Eau de Parfum Spray 60ml (2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=2.0,
        size_ml=60,
        volume_oz=2.0,
        volume_ml=60,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A modern unisex eau de parfum with spicy dark fruit up top, a rosy heart, and a soft caramel-vanilla base.",
        top_notes="Black Cherry, Pink Pepper",
        mid_notes="White Rose, Peony, Tonka Bean, Nutmeg",
        base_notes="Patchouli, Caramel, Vanilla",
        scent="Floral spicy sweet fruity",
        feature="eau de parfum spray; unisex; 60ml / 2 oz",
        keywords="Lattafa, Ana Abiyedh Scarlet, Eau De Parfum, Unisex, 60ml, 2 oz, Black Cherry, Pink Pepper, Rose, Caramel",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "60 mL / 2.0 oz bottle size.",
            "Cherry-rose profile with spicy warmth and soft caramel vanilla.",
        ],
        similar_to="Christian Louboutin La Rose",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Official and retailer positioning support unisex wear, while community reviews often describe it as feminine-leaning. Best source-backed guidance points to a dressier floral-spicy style rather than a bright casual fruity scent.",
        source_official_url="https://www.lattafa-usa.com/products/ana-abiyedh-scarlet",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-ana-abiyedh-scarlet-edp-spray-2-0-oz-fragrances-6290362349938.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ana-Abiyedh-Scarlet-113803.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/ana-abiyedh-scarlet",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/ANA_ABIYEDH_SCARLET.png?v=1756142896",
            "https://www.lattafa-usa.com/cdn/shop/files/ANA_ABIYEDH_SCARLET_BOX_BOTTLE.png?v=1756142940&width=810",
        ],
        official_discrepancy_note="Fragrantica presents this release as women's, while Lattafa USA, Jomashop, and Parfumo all support a unisex listing with a feminine lean.",
    ),
    ProductSeed(
        product_id=215,
        barcode="6291108738191",
        brand="Lattafa",
        name="Lattafa Ansaam Gold Eau de Parfum Spray 100ml (3.38 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A sweet unisex eau de parfum with sparkling citrus-pear brightness, soft floral sweetness, and a creamy vanilla-musk base.",
        top_notes="Mandarin Orange, Pear",
        mid_notes="Sweet Notes, Jasmine, Rose",
        base_notes="Vanilla, Musk, Raspberry",
        scent="Sweet fruity floral gourmand",
        feature="eau de parfum spray; unisex; 100ml / 3.38 oz",
        keywords="Lattafa, Ansaam Gold, Eau De Parfum, Unisex, 100ml, 3.38 oz, Mandarin Orange, Pear, Vanilla, Raspberry",
        highlights=[
            "Eau de parfum spray concentration.",
            "Sweet floral-fruity profile from Lattafa.",
            "100 mL / 3.38 oz bottle size.",
            "Creamy vanilla-musk drydown with playful pear and raspberry facets.",
        ],
        similar_to="Parfums de Marly Oriana / Kilian Love, Don't Be Shy",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Retailer and official support for this barcode lean unisex, but community sources describe it as strongly feminine-leaning. Source-backed wear guidance points to sweet playful daytime or evening use rather than formal austere wear.",
        source_official_url="https://www.lattafa-usa.com/products/ansaam-gold",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-ansaam-gold-edp-spray-3-38-oz-fragrances-6291108738191.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ansaam-Gold-82731.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/lattafa-pride/ansaam-gold",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/1_97553617-4548-450d-88eb-2fb032306f94.png?v=1749363699",
            "https://m.media-amazon.com/images/I/71xtzTYmB9L._SX466_.jpg",
        ],
        official_discrepancy_note="Fragrantica categorizes Ansaam Gold as women's, but Jomashop and the current retail listing for this barcode position it as unisex.",
    ),
    ProductSeed(
        product_id=255,
        barcode="850050062035",
        brand="Bharara",
        name="Bharara King Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Bharara Beauty",
        description_intro="A bold men's eau de parfum with bright citrus up top, a juicy fruity center, and a smooth amber-musky vanilla finish.",
        top_notes="Orange, Bergamot, Lemon",
        mid_notes="Fruity Notes",
        base_notes="Vanilla, White Musk, Amber",
        scent="Citrus fruity sweet amber",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Bharara, King, Eau De Parfum, Men, 100ml, 3.4 oz, Orange, Bergamot, Vanilla, White Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Bharara.",
            "100 mL / 3.4 oz bottle size.",
            "Bright citrus opening with a smooth musky vanilla base.",
        ],
        similar_to=None,
        verified_note="Verified from Bharara official, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to an easy crowd-pleasing citrus-fruity masculine style that works especially well for casual, social, and general signature-scent use.",
        source_official_url="https://www.bhararabeauty.com/products/bharara-king",
        source_jomashop_url="https://www.jomashop.com/bharara-mens-king-edp-spray-3-4-oz-fragrances-850050062035.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Bharara/King-74184.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/bharara/king-eau-de-parfum",
        image_sources=[
            "http://www.bhararabeauty.com/cdn/shop/files/Gemini_Generated_Image_eokjadeokjadeokj.png?v=1772746597",
        ],
    ),
    ProductSeed(
        product_id=256,
        barcode="6294015136470",
        brand="Armaf",
        name="Armaf Club De Nuit Sillage Eau de Parfum Spray 105ml (3.6 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.6,
        size_ml=105,
        volume_oz=3.6,
        volume_ml=105,
        product_form="Eau De Parfum",
        manufacturer="Sterling Perfumes Industries LLC",
        description_intro="A crisp unisex eau de parfum with sparkling citrus and violet leaf up top, floral elegance in the heart, and a musky woody base.",
        top_notes="Bergamot, Lemon, Lime, Black Currant, Violet Leaf, Ginger",
        mid_notes="Rose, Iris, Jasmine",
        base_notes="Ambroxan, Musk, Sandalwood, Cedar",
        scent="Citrus musky woody fresh spicy",
        feature="eau de parfum spray; unisex; 105ml / 3.6 oz",
        keywords="Armaf, Club De Nuit Sillage, Eau De Parfum, Unisex, 105ml, 3.6 oz, Bergamot, Violet Leaf, Iris, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Armaf's Club De Nuit line.",
            "105 mL / 3.6 oz bottle size.",
            "Bright citrus-musky profile with floral polish and woody depth.",
        ],
        similar_to="Creed Silver Mountain Water",
        verified_note="Verified from Armaf official, Jomashop, Fragrantica, and Parfumo. Community comparisons consistently place it near Silver Mountain Water territory, with source-backed guidance favoring fresh day wear, warm-weather use, and people who like brighter inky citrus musk profiles.",
        source_official_url="https://armaf.com/products/armaf-club-de-nuit-silage-men",
        source_jomashop_url="https://www.jomashop.com/armaf-unisex-club-de-nuit-sillage-edp-spray-3-6-oz-fragrances-6294015136470.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Armaf/Armaf-Club-de-Nuit-Sillage-64105.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Armaf/club-de-nuit-sillage-eau-de-parfum",
        image_sources=[
            "http://armaf.com/cdn/shop/files/68.png?v=1758576452&width=2048",
        ],
        official_discrepancy_note="Armaf's official page copy labels the scent 'for men' in the description, but Fragrantica, Parfumo, and the retailer listing support the broader unisex positioning used here.",
    ),
    ProductSeed(
        product_id=212,
        barcode="6294015164152",
        brand="Armaf",
        name="Armaf Club De Nuit Blue Iconic Eau de Parfum Spray 105ml (3.6 oz) Men's Perfume",
        gender="Men",
        size_oz=3.6,
        size_ml=105,
        volume_oz=3.6,
        volume_ml=105,
        product_form="Eau De Parfum",
        manufacturer="Sterling Perfumes Industries LLC",
        description_intro="A modern men's eau de parfum with grapefruit-mint freshness up top, a spicy aquatic heart, and a smoky woody amber base.",
        top_notes="Grapefruit, Lemon, Mint, Pink Pepper, Coriander",
        mid_notes="Ginger, Melon, Jasmine, Nutmeg",
        base_notes="Woody Notes, Incense, Sandalwood, Amber, Cedar, Patchouli, Labdanum",
        scent="Fresh spicy woody amber aromatic",
        feature="eau de parfum spray; men; 105ml / 3.6 oz",
        keywords="Armaf, Club De Nuit Blue Iconic, Eau De Parfum, Men, 105ml, 3.6 oz, Grapefruit, Mint, Ginger, Incense",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Armaf's Club De Nuit line.",
            "105 mL / 3.6 oz bottle size.",
            "Fresh spicy blue-style profile with smoky woody depth.",
        ],
        similar_to="Bleu de Chanel",
        verified_note="Verified from Armaf official, Jomashop, Fragrantica, and Parfumo. Source-backed community comparison most consistently points toward the Bleu de Chanel lane, making this a versatile masculine daily-wear and social-wear option rather than a heavy sweet evening scent.",
        source_official_url="https://armaf.com/products/club-de-nuit-blue-iconic-200ml",
        source_jomashop_url="https://www.jomashop.com/armaf-mens-club-de-nuit-blue-iconic-edp-spray-3-6-oz-fragrances-6294015164152.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Armaf/Armaf-Club-de-Nuit-Blue-Iconic-78475.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Armaf/club-de-nuit-iconic",
        image_sources=[
            "http://armaf.com/cdn/shop/files/35721_5.png?v=1767893934&width=2048",
            "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.78475.avif",
        ],
        official_discrepancy_note="The verified official Armaf page used here is the 200ml fragrance page, while the exact 105ml pack size was confirmed through Jomashop.",
    ),
    ProductSeed(
        product_id=257,
        barcode="3770004268207",
        brand="Dumont",
        name="Dumont Nitro Black Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Dumont Perfumes Factory L.L.C.",
        description_intro="A fruity men's eau de parfum with bright pineapple-citrus up top, smoky floral woods in the heart, and a musky vanilla-amber base.",
        top_notes="Pineapple, Bergamot, Black Currant, Apple",
        mid_notes="Birch, Pepper, Patchouli, Jasmine, Lavender, Rose",
        base_notes="Musk, Amber, Vanilla",
        scent="Fruity fresh spicy woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Dumont, Nitro Black, Eau De Parfum, Men, 100ml, 3.4 oz, Pineapple, Bergamot, Birch, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Dumont's Nitro line.",
            "100 mL / 3.4 oz bottle size.",
            "Pineapple-citrus opening with smoky woods and musky vanilla depth.",
        ],
        similar_to="Creed Aventus",
        verified_note="Verified from Dumont official, Jomashop, Fragrantica, and Parfumo. Community comparisons repeatedly place Nitro Black in the Aventus-style lane, with source-backed guidance favoring casual, social, and outdoor masculine wear more than formal or soft office use.",
        source_official_url="https://dumontparfums.com/products/nitro-black",
        source_jomashop_url="https://www.jomashop.com/dumont-mens-nitro-black-edp-spray-3-4-oz-fragrances-3770004268207.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Dumont/Nitro-Black-73022.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Dumont/Nitro_Black",
        image_sources=[
            "http://dumontparfums.com/cdn/shop/products/NitroBlack2.jpg?v=1751280801",
        ],
    ),
    ProductSeed(
        product_id=224,
        barcode="6290362344407",
        brand="Lattafa",
        name="Lattafa Yara Mini Collection Gift Set 20ml Total (0.68 oz) Women's Fragrance Set",
        gender="Women",
        size_oz=0.68,
        size_ml=20,
        volume_oz=0.68,
        volume_ml=20,
        product_form="Gift Set",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A four-piece women's mini fragrance set featuring Yara Pink, Yara Candy, Yara Tous, and Yara Moi in travel-friendly sizes for sampling, gifting, and everyday variety.",
        top_notes="Included minis: Yara Pink, Yara Candy, Yara Tous, Yara Moi",
        mid_notes="Each mini fragrance has its own individual note pyramid",
        base_notes="See highlights for the included Yara collection scents",
        scent="Mixed floral fruity gourmand set",
        feature="4 x 5ml mini sprays; women's fragrance gift set; total 20ml",
        keywords="Lattafa, Yara Mini Collection, Gift Set, Women, 20ml total, Yara Pink, Yara Candy, Yara Tous, Yara Moi",
        highlights=[
            "Gift set with four 5 mL mini fragrance sprays.",
            "Women's Yara collection discovery-style set.",
            "Total fill volume 20 mL / 0.68 oz.",
            "Includes Yara Pink, Yara Candy, Yara Tous, and Yara Moi.",
        ],
        similar_to=None,
        verified_note="Verified from official Lattafa USA and Jomashop. This is a true four-piece Yara mini set rather than one fragrance pyramid, so it is best positioned as a discovery, travel, or gifting set instead of a single-scent listing.",
        source_official_url="https://www.lattafa-usa.com/products/yara-collection-set",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-mini-set-gift-set-fragrances-6290362344407.html",
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/IMG-0323.png?v=1753249372",
            "https://cdn2.jomashop.com/media/catalog/product/cache/0ee3019724ce73007b606b54ba535a23/l/a/lattafa-ladies-mini-set-gift-set-fragrances-6290362344407.jpg?width=546&height=546",
        ],
    ),
    ProductSeed(
        product_id=60,
        barcode="6290360590189",
        brand="Lattafa",
        name="Lattafa Maahir Legacy Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright men's eau de parfum with sparkling lime-mint freshness, aromatic spice through the heart, and an ambroxan-woody base.",
        top_notes="Lime, Mint, Grapefruit, Lavender, Pineapple",
        mid_notes="Black Pepper, Juniper Berry, Rosemary, Geranium, Frankincense",
        base_notes="Ambroxan, Vetiver, Oakmoss, Tonka Bean, Cashmeran",
        scent="Citrus aromatic fresh spicy woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Maahir Legacy, Eau De Parfum, Men, 100ml, 3.4 oz, Lime, Mint, Grapefruit, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-aromatic profile with a woody ambroxan base.",
        ],
        similar_to="Parfums de Marly Sedley",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Community comparisons strongly place it in the Sedley-inspired lane, and source-backed wear guidance points to warm-weather daytime use, gym, office, and general fresh masculine wear.",
        source_official_url="https://www.lattafa-usa.com/products/maahir-legacy",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-maahir-legacy-edp-3-4-oz-fragrances-6290360590189.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Maahir-Legacy-82727.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/maahir-legacy",
        image_sources=[
            "http://www.lattafa-usa.com/cdn/shop/files/Maahir-Legacy-1.png?v=1747421494",
        ],
    ),
    ProductSeed(
        product_id=56,
        barcode="6291107459196",
        brand="Maison Alhambra",
        name="Maison Alhambra Delilah Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A romantic women's eau de parfum with tart lychee-rhubarb freshness, a lush rose-peony heart, and a creamy musky vanilla base.",
        top_notes="Lychee, Rhubarb, Bergamot",
        mid_notes="Turkish Rose, Peony, Lily",
        base_notes="White Musk, Cashmeran, Vanilla",
        scent="Floral fruity sweet creamy",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Delilah, Eau De Parfum, Women, 100ml, 3.4 oz, Lychee, Rhubarb, Turkish Rose, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fruity rose profile with creamy musky vanilla softness.",
        ],
        similar_to="Parfums de Marly Delina",
        verified_note="Verified from Maison Alhambra official, Jomashop, Fragrantica, and Parfumo. Community comparisons consistently place Delilah in the Delina-inspired lane, with source-backed guidance favoring feminine social wear, daytime elegance, and spring-to-fall use.",
        source_official_url="https://maisonalhambra.co/product/delilah-maison-alhambra-inspired-by-parfums-de-marly-delina/",
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-ladies-delilah-edp-spray-3-4-oz-fragrances-6291107459196.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Delilah-90273.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/maison-alhambra/delilah",
        image_sources=[
            "https://maisonalhambra.co/wp-content/uploads/2025/06/Delilah-Maison-Alhambra-3-1024x1024.jpg",
            "https://maisonalhambra.co/wp-content/uploads/2026/01/edited_2-2.webp",
        ],
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
