#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_thirteenth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=201,
        barcode="6291108733875",
        brand="Lattafa",
        name="Lattafa Bade'e Al Oud Amethyst Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rich unisex eau de parfum with pink pepper and bergamot on top, a lush twin-rose floral heart, and a warm oud-amber vanilla base.",
        top_notes="Pink Pepper, Bergamot",
        mid_notes="Turkish Rose, Bulgarian Rose, Jasmine",
        base_notes="Agarwood (Oud), Amber, Vanilla",
        scent="Rose oud amber floral",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Bade'e Al Oud Amethyst, Eau De Parfum, Unisex, 100ml, 3.4 oz, Rose, Oud, Amber, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa's Bade'e Al Oud line.",
            "100 mL / 3.4 oz bottle size.",
            "Rose-oud style with warm ambered vanilla depth.",
        ],
        similar_to="Initio Atomic Rose",
        verified_note="Verified from Fragrantica, Parfumo, and retailer support. Community comparison most often points toward Atomic Rose, with source-backed wear guidance favoring cooler weather, evenings, and rich rosy statement wear.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-badee-al-oud-amethyst-edp-spray-3-4-oz-fragrances-6291108733875.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Bade-e-Al-Oud-Amethyst-68214.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/bade-e-al-oud-amethyst",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.68214.jpg",
        ],
    ),
    ProductSeed(
        product_id=202,
        barcode="6298463856485",
        brand="Paris Corner",
        name="Paris Corner Qissa Pink Eau de Parfum Spray 100ml (3.38 oz) Women Perfume",
        gender="Women",
        size_oz=3.38,
        size_ml=100,
        volume_oz=3.38,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Paris Corner Perfumes LLC",
        description_intro="A sweet women's eau de parfum with coconut and apple up top, soft violet-rose florals in the heart, and a creamy vanilla-sugar woody base.",
        top_notes="Coconut, Apple",
        mid_notes="Violet, Rose, Jasmine",
        base_notes="Vanilla, Sugar, Sandalwood, Cedarwood, Patchouli",
        scent="Sweet creamy fruity floral",
        feature="eau de parfum spray; women; 100ml / 3.38 oz",
        keywords="Paris Corner, Qissa Pink, Eau De Parfum, Women, 100ml, 3.38 oz, Coconut, Apple, Violet, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Paris Corner.",
            "100 mL / 3.38 oz bottle size.",
            "Soft coconut-apple floral profile with creamy vanilla sugar finish.",
        ],
        similar_to=None,
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop retailer support. Source-backed wear guidance points to an easy sweet feminine scent for casual wear, spring and summer, and soft gourmand-floral preferences.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/paris-corner-ladies-qissa-pink-edp-spray-3-38-oz-fragrances-6298463856485.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/PARIS-CORNER/Qissa-Pink-98578.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/paris-corner/qissa-pink",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.98578.jpg",
        ],
        official_discrepancy_note="Parfumo labels Qissa Pink more broadly for women and men, while Fragrantica and retailer listings position it as women's.",
    ),
    ProductSeed(
        product_id=183,
        barcode="6290360592039",
        brand="Lattafa",
        name="Lattafa Peace & Love Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A creamy unisex eau de parfum with bergamot, almond, and blackcurrant on top, a graceful rose-tuberose heart, and a soft sandalwood-heliotrope vanilla base.",
        top_notes="Bergamot, Almond, Blackcurrant",
        mid_notes="Rose, Tuberose",
        base_notes="Sandalwood, Heliotrope, Vanilla",
        scent="Creamy floral almond powdery",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Peace & Love, Eau De Parfum, Unisex, 100ml, 3.4 oz, Almond, Blackcurrant, Rose, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy almond-floral profile with smooth vanilla sandalwood finish.",
        ],
        similar_to="Dries Van Noten Soie Malaquais / Amouage Guidance",
        verified_note="Verified from Lattafa USA, Fragrantica, Parfumo, and Jomashop support. Community comparison repeatedly points toward Soie Malaquais and Guidance-adjacent territory, with source-backed wear guidance favoring soft luxurious daily wear and cooler-weather elegance.",
        source_official_url="https://www.lattafa-usa.com/products/peace-love",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-peace-love-edp-spray-3-4-oz-fragrances-6290360592039.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Peace-Love-100386.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/lattafa-pride/peace-love",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.100386.jpg",
        ],
    ),
    ProductSeed(
        product_id=273,
        barcode="6290362346104",
        brand="Lattafa",
        name="Lattafa Pride King Of Arabia Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bold men's eau de parfum with bright bergamot and raspberry on top, a refined woody-orris heart, and a leathered vanilla-patchouli base.",
        top_notes="Bergamot, Raspberry",
        mid_notes="Cedarwood, Osmanthus, Orris",
        base_notes="Leather, Vanilla, Patchouli",
        scent="Leathery fruity woody sweet",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, King Of Arabia, Eau De Parfum, Men, 100ml, 3.4 oz, Bergamot, Raspberry, Leather, Patchouli",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Leathered fruity-woody style with smooth vanilla depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo. The official page and community fragrance sites disagree strongly on the note pyramid, so the saved structure follows the exact official product page tied to this barcode.",
        source_official_url="https://www.lattafa-usa.com/products/king-of-arabia",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/King-Of-Arabia-113195.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/lattafa-pride/king-of-arabia",
        image_sources=[],
        official_discrepancy_note="Fragrantica comments and Parfumo currently present a very different oud-heavy pyramid, but the exact official Lattafa USA barcode page now shows bergamot, raspberry, cedarwood, osmanthus, orris, leather, vanilla, and patchouli. The saved notes follow that official page.",
    ),
    ProductSeed(
        product_id=274,
        barcode="6290362347095",
        brand="Lattafa",
        name="Lattafa Pure Crystal Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A bright unisex eau de parfum with red berries, citrus, and cinnamon on top, a cognac-ginger aromatic heart, and a warm amber-vanilla woody base.",
        top_notes="Red Berries, Cinnamon, Bitter Orange, Grapefruit, Bergamot",
        mid_notes="Cognac, Ginger, Clary Sage",
        base_notes="Amber, Sandalwood, Vanilla, Vetiver, Cardamom, Musk, Patchouli",
        scent="Woody warm spicy amber fruity",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Pure Crystal, Eau De Parfum, Unisex, 100ml, 3.4 oz, Red Berries, Cognac, Ginger, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Citrus-berry opening with aromatic cognac heart and warm woody amber base.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo. The note pyramid aligns cleanly across those sources, and the wear profile leans best to cooler evenings or dressed-up social use rather than hot-weather freshness.",
        source_official_url="https://www.lattafa-usa.com/products/pure-crystal",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Pure-Crystal-118006.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/lattafa-pride/pure-crystal",
        image_sources=[],
    ),
    ProductSeed(
        product_id=213,
        barcode="6290362347132",
        brand="Lattafa",
        name="Lattafa Pride Queen Of Roses Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A feminine eau de parfum with rose and pink pepper on top, saffron and patchouli in the heart, and a warm vanilla-musk amber base.",
        top_notes="Pink Pepper, Rose",
        mid_notes="Patchouli, Saffron",
        base_notes="Musk, Vanilla, Amber",
        scent="Rose spicy sweet musky",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Queen Of Roses, Eau De Parfum, Women, 100ml, 3.4 oz, Rose, Pink Pepper, Saffron, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa Pride.",
            "100 mL / 3.4 oz bottle size.",
            "Rosy spicy profile with warm musky vanilla amber finish.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA and barcode-linked retailer support. Public community pages are thinner on this release, so the saved note pyramid follows the exact official product page tied to this barcode.",
        source_official_url="https://www.lattafa-usa.com/products/queen-of-roses",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="Retailer blurbs vary on the detailed pyramid, but the exact official Lattafa USA barcode page supports the saved rose, saffron, patchouli, vanilla, amber, and musk structure.",
    ),
    ProductSeed(
        product_id=216,
        barcode="6298043161695",
        brand="Lattafa",
        name="Lattafa Ra'ed Absolu Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A refined unisex eau de parfum with bergamot, saffron, and pink pepper on top, a floral rose-jasmine heart, and a creamy vanilla-patchouli base.",
        top_notes="Bergamot, Saffron, Pink Pepper",
        mid_notes="Rose, Jasmine",
        base_notes="Vanilla, Sandalwood, Amber, Patchouli, Musk",
        scent="Citrus sweet floral musky",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Ra'ed Absolu, Eau De Parfum, Unisex, 100ml, 3.4 oz, Saffron, Rose, Vanilla, Patchouli",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Refined floral-spiced profile with creamy vanilla and patchouli finish.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA and Fragrantica. The official page and fragrance-reference coverage align cleanly enough to save the full pyramid, with wear leaning toward polished daytime-to-evening versatility.",
        source_official_url="https://www.lattafa-usa.com/products/raed-absolu",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ra-ed-Absolu-131196.html",
        source_parfumo_url=None,
        image_sources=[],
    ),
    ProductSeed(
        product_id=210,
        barcode="6298043161701",
        brand="Lattafa",
        name="Lattafa Ra'ed Intensely Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fresh unisex eau de parfum with bright grapefruit, bergamot, and yuzu on top, a soft ambergris heart, and a smooth musky sandalwood base.",
        top_notes="Grapefruit, Bergamot, Yuzu",
        mid_notes="White Florals, Black Pepper, Ambergris",
        base_notes="Sandalwood, Ambroxan, Musk",
        scent="Fresh citrus musky woody",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Ra'ed Intensely, Eau De Parfum, Unisex, 100ml, 3.4 oz, Grapefruit, Yuzu, Ambergris, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Bright citrus opening with a polished musky woody finish.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, and Parfumo. The note pyramid aligns well across those sources, and the scent profile fits fresh signature wear, daytime use, and warm-weather versatility.",
        source_official_url="https://www.lattafa-usa.com/products/raed-intensely",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ra-ed-Intensely-131200.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/ra-ed-intensely",
        image_sources=[],
    ),
    ProductSeed(
        product_id=275,
        barcode="6290362340492",
        brand="Asdaaf",
        name="Asdaaf Raneen Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A radiant women's eau de parfum with dragon fruit, pear, and mandarin on top, a floral freesia-jasmine heart, and a warm vanilla-tonka amber base.",
        top_notes="Dragon Fruit, Pear, Mandarin",
        mid_notes="Jasmine, Freesia, Orange Flower",
        base_notes="Musk, Vanilla, Tonka Bean, Amber",
        scent="Sweet fruity floral feminine",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Asdaaf, Raneen, Eau De Parfum, Women, 100ml, 3.4 oz, Dragon Fruit, Pear, Freesia, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Asdaaf.",
            "100 mL / 3.4 oz bottle size.",
            "Bright tropical-fruity opening with floral heart and creamy amber finish.",
        ],
        similar_to=None,
        verified_note="Verified from the official Lattafa USA barcode page and Parfumo. The official source provides a clean complete pyramid, and the overall scent direction fits cheerful feminine daily wear.",
        source_official_url="https://lattafa-usa.com/products/asdaaf-raneen-eau-de-parfum-for-women",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url="https://www.parfumo.com/Perfumes/Asdaaf/raneen",
        image_sources=[],
        official_discrepancy_note="Raneen is sold under the Asdaaf line but marketed by Lattafa, so the product uses Asdaaf as brand and Lattafa as manufacturer.",
    ),
    ProductSeed(
        product_id=69,
        barcode="614514331026",
        brand="Rasasi",
        name="Rasasi Hawas Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Rasasi Perfumes Industry LLC",
        description_intro="A fresh men's eau de parfum with apple, bergamot, lemon, and cinnamon on top, watery fruity florals in the heart, and a musky ambergris driftwood base.",
        top_notes="Apple, Bergamot, Lemon, Cinnamon",
        mid_notes="Watery Notes, Plum, Orange Blossom, Cardamom",
        base_notes="Ambergris, Musk, Patchouli, Driftwood",
        scent="Fresh fruity aquatic sweet",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Rasasi, Hawas, Eau De Parfum, Men, 100ml, 3.4 oz, Apple, Watery Notes, Ambergris, Driftwood",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Rasasi.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh fruity-aquatic style with musky ambergris depth.",
        ],
        similar_to="Rabanne Invictus / Invictus Aqua",
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop retailer support. Community comparison most often points toward the Invictus family, and the source-backed wear fit is warm-weather daytime use, gym/casual rotation, and crowd-pleasing freshness.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/rasasi-men-hawas-edp-spray-3-4-oz-fragrances-614514331026.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Rasasi/Hawas-for-Him-46890.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Rasasi/Hawas_for_Men",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.46890.jpg",
        ],
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
