#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (  # noqa: E402
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_remainder03_report.json"

COMMON_OIL_INGREDIENTS = "Parfum (Fragrance), carrier oils, fixatives, and stabilizers."
COMMON_SPRAY_INGREDIENTS = "Alcohol Denat., Parfum (Fragrance), Aqua (Water), fragrance compounds, fixatives, and stabilizers."


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=203,
        barcode="6290171073840",
        brand="Afnan",
        name="Afnan Mystique Bouquet Eau de Parfum Spray 80ml (2.7 oz) Women Perfume",
        gender="Women",
        size_oz=2.7,
        size_ml=80,
        volume_oz=2.7,
        volume_ml=80,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A luminous women's eau de parfum with juicy peach, citrus, and lychee on top, a floral peony-orange blossom heart, and a soft ambroxan-vanilla musky base.",
        top_notes="White Peach, Mandarin Orange, Bergamot, Litchi",
        mid_notes="Peony, Orange Blossom, Vetiver, Mahonia",
        base_notes="Musk, Ambroxan, Oak Moss, Vanilla",
        scent="Floral fruity musky soft",
        feature="eau de parfum spray; women; 80ml / 2.7 oz",
        keywords="Afnan, Mystique Bouquet, Eau De Parfum, Women, 80ml, 2.7 oz, Peach, Litchi, Peony, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Afnan.",
            "80 mL / 2.7 oz bottle size.",
            "Juicy floral profile with soft musky vanilla depth.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing note pyramid and exact barcode-backed size support for the 80ml / 2.7 oz bottle. This pass standardizes the title, size fields, and SDS.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=38,
        barcode="6290171075073",
        brand="Afnan",
        name="Afnan Supremacy Collector's Edition Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A refined men's eau de parfum with bright pineapple and bergamot up top, smoky ambered florals through the heart, and a mossy musky ambergris base.",
        top_notes="Pineapple, Bergamot, Apple, White Floral",
        mid_notes="Orange Blossom, Birch, Amber",
        base_notes="Oak Moss, Musk, Ambergris",
        scent="Fresh fruity woody musky",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Afnan, Supremacy Collector's Edition, Eau De Parfum, Men, 100ml, 3.4 oz, Pineapple, Birch, Oak Moss, Ambergris",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Afnan.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh fruity-woody profile with mossy musky depth.",
        ],
        similar_to="Creed Aventus / Creed Absolu Aventus",
        verified_note="Completed from the product's existing verified note pyramid and exact official size support for the 100ml / 3.4 oz bottle. This pass fixes the incomplete title and adds the missing SDS.",
        source_official_url="https://us.afnan.com/products/supremacy-collectors-edition",
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=167,
        barcode="6290171076001",
        brand="Afnan",
        name="Afnan Turathi Electric Eau de Parfum Spray 90ml (3.0 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.0,
        size_ml=90,
        volume_oz=3.0,
        volume_ml=90,
        product_form="Eau De Parfum",
        manufacturer="Afnan Perfumes LLC",
        description_intro="A bright unisex eau de parfum with juicy pear and citrus on top, a fruity woody heart, and a smooth amber-vanilla musky base.",
        top_notes="Pear, Pink Grapefruit, Mandarin Orange, Bergamot",
        mid_notes="Orange Blossom, Apple, Cedarwood",
        base_notes="Musk, Amber, Vanilla, Ambroxan",
        scent="Fresh fruity amber musky",
        feature="eau de parfum spray; unisex; 90ml / 3.0 oz",
        keywords="Afnan, Turathi Electric, Eau De Parfum, Unisex, 90ml, 3.0 oz, Pear, Grapefruit, Amber, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Afnan.",
            "90 mL / 3.0 oz bottle size.",
            "Bright fruity-citrus profile with amber-vanilla base.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and exact 90ml / 3.0 oz barcode-backed size support. This pass fills the missing structure and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=19,
        barcode="6291110111708",
        brand="Al Rehab",
        name="Al Rehab Overdose Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A rich oriental gourmand eau de parfum with spiced citrus on top, a praline-date floral heart, and a deep tonka-vanilla benzoin base.",
        top_notes="Cinnamon, Nutmeg, Bergamot",
        mid_notes="Praline, Tuberose, Dates",
        base_notes="Tonka Bean, Vanilla, Benzoin",
        scent="Oriental gourmand sweet spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Al Rehab, Overdose, Eau De Parfum, Unisex, 100ml, 3.4 oz, Cinnamon, Praline, Dates, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "100 mL / 3.4 oz bottle size.",
            "Sweet oriental-gourmand profile with spicy vanilla depth.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and standard 100ml Al Rehab spray format. This pass fills the missing size, gender normalization, and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=30,
        barcode="6281110100598",
        brand="Al Rehab",
        name="Al Rehab Ameer Eau de Parfum Spray 50ml (1.65 oz) Men Perfume",
        gender="Men",
        size_oz=1.65,
        size_ml=50,
        volume_oz=1.65,
        volume_ml=50,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A regal men's eau de parfum with aldehydic lavender and saffron on top, a floral cedar heart, and a warm patchouli-vanilla amber base.",
        top_notes="Aldehydes, Lavender, Saffron, Orange, Rose",
        mid_notes="Geranium, Cedar",
        base_notes="Patchouli, Vanilla, Oakmoss, Amber, Musk",
        scent="Aromatic oriental woody warm",
        feature="eau de parfum spray; men; 50ml / 1.65 oz",
        keywords="Al Rehab, Ameer, Eau De Parfum, Men, 50ml, 1.65 oz, Lavender, Saffron, Patchouli, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Al Rehab.",
            "50 mL / 1.65 oz bottle size.",
            "Aromatic oriental style with warm woody-amber depth.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and typical 50ml Al Rehab spray format. This pass standardizes the title and adds missing size and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=16,
        barcode="6291110111906",
        brand="Al Rehab",
        name="Al Rehab Spanish Vanilla Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A comforting unisex gourmand eau de parfum with creamy milk on top, a rich vanilla heart, and sugary sweetness in the base.",
        top_notes="Milk",
        mid_notes="Vanilla",
        base_notes="Sugar",
        scent="Vanilla lactonic sweet soft",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Al Rehab, Spanish Vanilla, Eau De Parfum, Unisex, 100ml, 3.4 oz, Milk, Vanilla, Sugar",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy vanilla profile with soft sugary warmth.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and the standard 100ml Al Rehab spray format. This pass fills the missing size and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
    ProductSeed(
        product_id=9,
        barcode="6291110116307",
        brand="Al Rehab",
        name="Al Rehab Choco Musk Pistachio Perfume Oil 6ml (0.2 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=0.2,
        size_ml=6,
        volume_oz=0.2,
        volume_ml=6,
        product_form="Perfume Oil",
        manufacturer="Al Rehab Perfumes",
        description_intro="A rich unisex perfume oil with pistachio and musk on top, cacao in the heart, and a warm vanilla-amber base.",
        top_notes="Pistachio, Musk",
        mid_notes="Cacao",
        base_notes="Vanilla, Amber",
        scent="Nutty sweet gourmand warm",
        feature="perfume oil roll-on; unisex; 6ml / 0.2 oz",
        keywords="Al Rehab, Choco Musk Pistachio, Perfume Oil, Unisex, 6ml, 0.2 oz, Pistachio, Cacao, Vanilla, Amber",
        highlights=[
            "Concentrated perfume oil format.",
            "Unisex fragrance from Al Rehab.",
            "6 mL / 0.2 oz travel-friendly size.",
            "Nutty pistachio-cacao profile with warm vanilla-amber depth.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing note pyramid and exact title-based 6ml oil sizing. This pass fills the missing structure and SDS fields only.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_OIL_INGREDIENTS,
    ),
    ProductSeed(
        product_id=18,
        barcode="6291110100078",
        brand="Al Rehab",
        name="Al Rehab French Coffee Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Al Rehab Perfumes",
        description_intro="A creamy unisex gourmand eau de parfum with cocoa and sugar up top, a rich coffee-caramel heart, and warm cinnamon-vanilla depth in the base.",
        top_notes="Cocoa, Sugar",
        mid_notes="Coffee, Caramel, Cream, Milk",
        base_notes="Cinnamon, Vanilla",
        scent="Coffee gourmand creamy sweet",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Al Rehab, French Coffee, Eau De Parfum, Unisex, 100ml, 3.4 oz, Coffee, Caramel, Cocoa, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Al Rehab.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy coffee-gourmand profile with warm cinnamon vanilla finish.",
        ],
        similar_to=None,
        verified_note="Completed from the product's existing verified note pyramid and the exact 100ml / 3.4 oz naming already present. This pass fills the missing structure and SDS fields.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        ingredients=COMMON_SPRAY_INGREDIENTS,
    ),
]


def main() -> int:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(json.dumps(results, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
