#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from server.company_db import get_product, utc_now
from server.postgres_cutover import POSTGRES_SIDECAR_SCHEMA, _pg_connect
from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    build_gallery,
    category_name_for_gender,
    description_html,
    description_text,
    volume_text,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_seventh10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=136,
        barcode="6291107456058",
        brand="Lattafa",
        name="Lattafa Fakhar Black Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A fresh aromatic men's fragrance with apple, bergamot, and ginger in the opening, a clean herbaceous heart, and a smooth tonka-amberwood base.",
        top_notes="Apple, Bergamot, Ginger",
        mid_notes="Lavender, Sage, Juniper Berries, Geranium",
        base_notes="Tonka Bean, Cedar, Amberwood, Vetiver",
        scent="Fresh aromatic woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Fakhar Black, Eau De Parfum, Men, 100ml, 3.4 oz, Apple, Bergamot, Lavender, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh aromatic profile with herbal depth and warm woody drydown.",
        ],
        similar_to="Yves Saint Laurent Y Eau de Parfum",
        verified_note="Verified from Lattafa USA, Jomashop, and Fragrantica. Source-backed wear guidance consistently places Fakhar Black in the easy everyday fresh-aromatic lane, especially for office wear, warm weather, and mass-appeal masculine use.",
        source_official_url="https://www.lattafa-usa.com/products/fakhar-men",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-fakhar-edp-spray-3-4-oz-fragrances-6291107456058.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Fakhar-Black-70465.html",
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-fakhar-edp-spray-3-4-oz-fragrances-6291107456058.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.70465.jpg",
        ],
    ),
    ProductSeed(
        product_id=55,
        barcode="6291107456041",
        brand="Lattafa",
        name="Lattafa Fakhar Rose Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A lush fruity-floral women's fragrance with sparkling fruits and pomegranate up top, an opulent white-floral heart, and a soft musky vanilla finish.",
        top_notes="Fruits, Lily, Pomegranate, Aldehydes",
        mid_notes="Tuberose, Jasmine, Gardenia, Ylang-Ylang, Honeysuckle, Rose, Peony",
        base_notes="Vanilla, White Musk, Sandalwood, Ambroxan",
        scent="Floral fruity sweet",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Fakhar Rose, Eau De Parfum, Women, 100ml, 3.4 oz, Pomegranate, Tuberose, Jasmine, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fruity white-floral profile with soft musky vanilla drydown.",
        ],
        similar_to=None,
        verified_note="Verified from the current Lattafa USA product page, Jomashop, and Fragrantica. Source-backed wear guidance points to a feminine floral-fruity profile best suited to daily wear, spring-friendly styling, and dressier daytime use.",
        source_official_url="https://www.lattafa-usa.com/products/fakhar",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-fakhar-edp-spray-3-4-oz-fragrances-6291107456041.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Fakhar-Rose-70466.html",
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-ladies-fakhar-edp-spray-3-4-oz-fragrances-6291107456041.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.70466.jpg",
        ],
        official_discrepancy_note="An older archived official page used a simplified orange-blossom / tuberose / jasmine / vetiver / patchouli structure, but the current exact official store page aligns with Fragrantica on the fuller fruits-lily-pomegranate floral pyramid, so that is the saved version.",
    ),
    ProductSeed(
        product_id=219,
        barcode="6290360593166",
        brand="Lattafa",
        name="Lattafa Fakhar Gold Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A warm amber-woody fragrance with a salty tuberose opening, a rich amber-tonka heart, and a dry vetiver-labdanum base.",
        top_notes="Tuberose, Salt",
        mid_notes="Amber, Tonka Bean, Cashmeran",
        base_notes="Cedarwood, Vetiver, Labdanum",
        scent="Amber woody white floral",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Fakhar Gold, Eau De Parfum, Unisex, 100ml, 3.4 oz, Tuberose, Amber, Tonka Bean, Labdanum",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Warm amber-woody profile with tuberose and tonka depth.",
        ],
        similar_to=None,
        verified_note="Verified from the exact Jomashop barcode page and Fragrantica. No exact official Lattafa USA page was confirmed for this barcode, so the note pyramid and positioning follow the aligned retailer and fragrance-database sources only.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-fakhar-gold-edp-3-4-oz-fragrances-6290360593166.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Fakhar-Gold-128690.html",
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-fakhar-gold-edp-3-4-oz-fragrances-6290360593166.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.128690.jpg",
        ],
        official_discrepancy_note="No exact official Lattafa USA page was confirmed for Fakhar Gold during this pass, so the saved record stays anchored to the exact Jomashop page plus Fragrantica.",
    ),
    ProductSeed(
        product_id=208,
        barcode="6290362345817",
        brand="Lattafa",
        name="Lattafa Fakhar Platin Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A modern spicy-woody fragrance with bergamot, pink pepper, and cardamom up top, a ginger-lavender-guava heart, and a smoky palo santo base.",
        top_notes="Bergamot, Pink Pepper, Cardamom",
        mid_notes="Ginger, Lavender, Guava",
        base_notes="Palo Santo, Incense, Sandalwood",
        scent="Fresh spicy woody aromatic",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Fakhar Platin, Eau De Parfum, Unisex, 100ml, 3.4 oz, Bergamot, Guava, Palo Santo, Incense",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Spicy-woody profile with guava brightness and smoky palo santo depth.",
        ],
        similar_to=None,
        verified_note="Verified from the exact Lattafa USA product page, Jomashop, and Fragrantica. Source-backed wear guidance points to a polished fresh-spicy profile that works best when you want something smoother and smokier than a typical citrus freshie.",
        source_official_url="https://www.lattafa-usa.com/products/fakhar-platin",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-fakhar-platin-edp-spray-3-4-oz-fragrances-6290362345817.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Fakhar-Platin-107363.html",
        source_parfumo_url=None,
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-fakhar-platin-edp-spray-3-4-oz-fragrances-6290362345817.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.107363.jpg",
        ],
    ),
    ProductSeed(
        product_id=44,
        barcode="6290360598864",
        brand="Lattafa",
        name="Lattafa Habik for Men Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A spicy-oriental men's fragrance with cardamom and pepper up top, an aromatic lavender-cinnamon heart, and a warm sandalwood-tonka base.",
        top_notes="Cardamom, Pepper, Artemisia, Bergamot",
        mid_notes="Sage, Lavender, Cinnamon",
        base_notes="Sandalwood, Patchouli, Tonka Bean, Amberwood, Musk",
        scent="Spicy oriental woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Habik for Men, Eau De Parfum, Men, 100ml, 3.4 oz, Cardamom, Pepper, Lavender, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Spicy oriental profile with aromatic heart and warm woody base.",
        ],
        similar_to="Jean Paul Gaultier Le Male Essence de Parfum",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance places Habik Men in the stronger dressed-up masculine lane, especially for cooler weather and evening use.",
        source_official_url="https://www.lattafa-usa.com/products/habik-for-men-pre-order",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-habik-edp-spray-3-4-oz-fragrances-6290360598864.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Habik-For-Men-110353.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/habik-men",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-habik-edp-spray-3-4-oz-fragrances-6290360598864.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.110353.jpg",
        ],
    ),
    ProductSeed(
        product_id=196,
        barcode="6290360599489",
        brand="Lattafa",
        name="Lattafa Habik for Women Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A bright floral-fruity women's fragrance with bergamot and pear in the opening, a soft freesia-jasmine heart, and a smooth amber-musk base.",
        top_notes="Bergamot, Pear",
        mid_notes="Jasmine, Lily of the Valley, Freesia",
        base_notes="Musk, Dry Amber, Oakmoss",
        scent="Floral fruity fresh",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Habik for Women, Eau De Parfum, Women, 100ml, 3.4 oz, Bergamot, Pear, Freesia, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Floral-fruity profile with airy freshness and musky amber finish.",
        ],
        similar_to="Versace pour Femme Dylan Purple Eau de Parfum",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance places Habik Women in the easy daily feminine lane, especially for spring and daytime wear.",
        source_official_url="https://www.lattafa-usa.com/products/habik-for-women-preorder",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-habik-edp-spray-3-4-oz-fragrances-6290360599489.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Habik-For-Women-110354.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/habik-women",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-ladies-habik-edp-spray-3-4-oz-fragrances-6290360599489.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.110354.jpg",
        ],
    ),
    ProductSeed(
        product_id=59,
        barcode="6290360599120",
        brand="Lattafa",
        name="Lattafa Her Confession Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A creamy sweet women's fragrance with cinnamon and Mystikal in the opening, white florals and incense through the heart, and a soft vanilla-tonka musk base.",
        top_notes="Mystikal, Cinnamon",
        mid_notes="Tuberose, Jasmine, Incense, Mahonial",
        base_notes="Vanilla, Tonka Bean, Musk",
        scent="Creamy sweet floral",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Her Confession, Eau De Parfum, Women, 100ml, 3.4 oz, Cinnamon, Tuberose, Vanilla, Tonka Bean",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy sweet floral profile with incense and vanilla warmth.",
        ],
        similar_to="Liquides Imaginaires Blanche Bete",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance consistently places Her Confession in the creamy cozy feminine lane with strong appeal for cooler weather, softer evening wear, and sweet lactonic styling.",
        source_official_url="https://www.lattafa-usa.com/products/her-confession",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-her-confession-edp-spray-3-4-oz-fragrances-6290360599120.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Her-Confession-96864.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/her-confession",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-ladies-her-confession-edp-spray-3-4-oz-fragrances-6290360599120.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.96864.jpg",
        ],
    ),
    ProductSeed(
        product_id=66,
        barcode="6290360599113",
        brand="Lattafa",
        name="Lattafa His Confession Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A smooth modern masculine fragrance with mandarin, cinnamon, and lavender in the opening, iris and benzoin depth in the heart, and a warm vanilla-incense base.",
        top_notes="Cinnamon, Lavender, Mandarin",
        mid_notes="Iris, Benzoin, Cypress, Mahonial",
        base_notes="Vanilla, Tonka Bean, Amber, Cedarwood, Incense, Patchouli",
        scent="Warm sweet woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, His Confession, Eau De Parfum, Men, 100ml, 3.4 oz, Mandarin, Iris, Vanilla, Incense",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Smooth warm profile with iris, incense, and vanilla-tonka depth.",
        ],
        similar_to="Givenchy Gentleman Eau de Parfum",
        verified_note="Verified from Lattafa USA, Jomashop listing support, Fragrantica, and Parfumo. Source-backed wear guidance points to a crowd-pleasing modern masculine scent that works best for cooler weather, casual evenings, and dressed-up daily wear.",
        source_official_url="https://www.lattafa-usa.com/products/his-confession",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-his-confession-edp-spray-3-4-oz-fragrances-6290360599113.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/His-Confession-96866.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/his-confession",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-his-confession-edp-spray-3-4-oz-fragrances-6290360599113.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.96866.jpg",
        ],
    ),
    ProductSeed(
        product_id=36,
        barcode="6291108737194",
        brand="Lattafa",
        name="Lattafa Khamrah Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A rich sweet-gourmand fragrance with cinnamon and nutmeg up top, a warm dates-praline heart, and a deep vanilla-resinous base.",
        top_notes="Cinnamon, Nutmeg, Bergamot",
        mid_notes="Dates, Praline, Tuberose, Mahonial",
        base_notes="Vanilla, Tonka Bean, Amberwood, Myrrh, Benzoin, Akigalawood",
        scent="Sweet gourmand spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Khamrah, Eau De Parfum, Unisex, 100ml, 3.4 oz, Cinnamon, Dates, Praline, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Spiced gourmand profile with dates, praline, and resinous vanilla depth.",
        ],
        similar_to="By Kilian Angels' Share",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance firmly places Khamrah in the cooler-weather gourmand lane with strong evening, cozy, and special-occasion use.",
        source_official_url="https://www.lattafa-usa.com/products/khamrah",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-khamrah-edp-spray-3-4-oz-fragrances-6291108737194.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-75805.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/khamrah",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-khamrah-edp-spray-3-4-oz-fragrances-6291108737194.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.75805.jpg",
        ],
    ),
    ProductSeed(
        product_id=37,
        barcode="6290360593661",
        brand="Lattafa",
        name="Lattafa Khamrah Qahwa Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A richer coffee-leaning gourmand with cinnamon, cardamom, and ginger up top, a sweet praline-fruit heart, and a warm vanilla-coffee tonka base.",
        top_notes="Cinnamon, Cardamom, Ginger",
        mid_notes="Praline, Candied Fruits, White Flowers",
        base_notes="Vanilla, Coffee, Tonka Bean, Benzoin, Musk",
        scent="Gourmand sweet spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Khamrah Qahwa, Eau De Parfum, Unisex, 100ml, 3.4 oz, Cardamom, Coffee, Praline, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Coffee-spiced gourmand profile with praline sweetness and warm resinous depth.",
        ],
        similar_to="By Kilian Angels' Share",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance places Khamrah Qahwa in the stronger cold-weather gourmand lane with date-night and evening appeal, especially for coffee-tinged sweet scent fans.",
        source_official_url="https://www.lattafa-usa.com/products/khamrah-qahwa",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-khamrah-qahwa-edp-spray-3-4-oz-fragrances-6290360593661.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-Qahwa-88175.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/khamrah-qahwa",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-khamrah-qahwa-edp-spray-3-4-oz-fragrances-6290360593661.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.88175.jpg",
        ],
    ),
]


def update_product(seed: ProductSeed) -> dict[str, Any]:
    current = get_product(seed.product_id) or {}
    primary_image, gallery_json = build_gallery(seed, current)
    now = utc_now()
    updates = {
        "name": seed.name,
        "brand": seed.brand,
        "gender": seed.gender,
        "description": description_text(seed),
        "notes": seed.verified_note,
        "note_top": seed.top_notes,
        "note_mid": seed.mid_notes,
        "note_base": seed.base_notes,
        "size_oz": seed.size_oz,
        "size_ml": seed.size_ml,
        "volume_oz": seed.volume_oz,
        "volume_ml": seed.volume_ml,
        "media_url": primary_image,
        "image_gallery_urls": gallery_json,
        "notes_verified": 1,
        "notes_verified_at": now,
        "similar_to": seed.similar_to,
        "dupe_inspiration": seed.similar_to,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "tiktok_title": seed.name,
        "tiktok_item_name": seed.name,
        "tiktok_category_name": category_name_for_gender(seed.gender),
        "tiktok_brand": seed.brand,
        "tiktok_manufacturer": seed.manufacturer,
        "tiktok_feature": seed.feature,
        "tiktok_search_keywords": seed.keywords,
        "tiktok_scent": seed.scent,
        "tiktok_product_form": seed.product_form,
        "tiktok_fragrance_concentration": seed.product_form,
        "tiktok_volume": volume_text(seed),
        "tiktok_description": description_html(seed),
        "tiktok_highlights": "\n".join(seed.highlights),
        "tiktok_pack_type": "Single item" if seed.product_form != "Gift Set" else "Gift set",
        "tiktok_container_type": "Spray" if seed.product_form != "Gift Set" else "Multi-item set",
        "tiktok_age_group": "Adult",
        "tiktok_region_of_origin": "United Arab Emirates",
        "updated_at": now,
    }
    if seed.ingredients is not None:
        updates["ingredients"] = seed.ingredients
        updates["tiktok_ingredients"] = seed.ingredients
    if seed.package_weight_oz is not None:
        updates["tiktok_package_weight_oz"] = seed.package_weight_oz
    assignments = ", ".join(f"{column} = %s" for column in updates)
    params = list(updates.values()) + [seed.product_id]
    conn = _pg_connect()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"UPDATE {POSTGRES_SIDECAR_SCHEMA}.products SET {assignments} WHERE id = %s",
                    params,
                )
    finally:
        conn.close()
    return {
        "product_id": seed.product_id,
        "barcode": seed.barcode,
        "name": seed.name,
        "gallery_count": 0 if not gallery_json else len(json.loads(gallery_json)),
        "primary_image": primary_image,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "discrepancy_note": seed.official_discrepancy_note,
    }


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
