#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from server.company_db import get_product, utc_now
from server.postgres_cutover import POSTGRES_SIDECAR_SCHEMA, _pg_connect
from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    build_gallery,
    category_name_for_gender,
    description_html,
    description_text,
    volume_text,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_sixth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=57,
        barcode="6290362346548",
        brand="Lattafa",
        name="Lattafa Asad Elixir Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A denser spicy-amber men's fragrance with grapefruit and saffron up top, smoky tobacco-vanilla depth through the heart, and a resinous woody finish.",
        top_notes="Pink Pepper, Saffron, Grapefruit",
        mid_notes="Tobacco, Cedarwood, Vanilla",
        base_notes="Patchouli, Olibanum, Cashmeran, Dry Amber",
        scent="Spicy sweet woody amber",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Asad Elixir, Eau De Parfum, Men, 100ml, 3.4 oz, Saffron, Grapefruit, Tobacco, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Spicy amber profile with tobacco, vanilla, and resinous depth.",
        ],
        similar_to="Dior Sauvage Elixir",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance consistently places Asad Elixir in the stronger evening, cooler-weather, dressed-up masculine lane rather than as a fresh daytime grab.",
        source_official_url="https://www.lattafa-usa.com/products/asad-elixir",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-asad-elixir-edp-spray-3-4-oz-fragrances-6290362346548.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-Elixir-117616.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/asad-elixir-elixir",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-asad-elixir-edp-spray-3-4-oz-fragrances-6290362346548.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.117616.jpg",
        ],
    ),
    ProductSeed(
        product_id=65,
        barcode="6290360598666",
        brand="Lattafa",
        name="Lattafa Asad Zanzibar Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A creamy tropical men's fragrance with black pepper and lavender in the opening, salty coconut-iris depth through the heart, and smooth vanilla incense in the drydown.",
        top_notes="Lavender, Black Pepper",
        mid_notes="Coconut Water, Iris, Salt",
        base_notes="Vanilla, Incense",
        scent="Sweet creamy aquatic spicy",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Asad Zanzibar, Eau De Parfum, Men, 100ml, 3.4 oz, Lavender, Coconut Water, Iris, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy tropical profile with coconut water, salt, and vanilla incense.",
        ],
        similar_to="Jean Paul Gaultier Le Beau Paradise Garden",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to warmer weather, daytime to early-evening casual wear, and buyers who want a sweeter tropical profile instead of the darker original Asad style.",
        source_official_url="https://www.lattafa-usa.com/products/asad-zanzibar",
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-asad-zanzibar-edp-3-4-oz-fragrances-6290360598666.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-Zanzibar-90713.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/asad-zanzibar",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-asad-zanzibar-edp-3-4-oz-fragrances-6290360598666.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.90713.jpg",
        ],
    ),
    ProductSeed(
        product_id=276,
        barcode="6290362347101",
        brand="Lattafa",
        name="Lattafa Asad Zanzibar Limited Edition Eau de Parfum Spray 100ml (3.4 oz) Men's Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A more polished marine-spicy take on the Zanzibar theme, opening with lavender and pink pepper before settling into soapy woods and a warm amber-tonka base.",
        top_notes="Marine Notes, Lavender, Pink Pepper",
        mid_notes="Soap, Cashmeran, Cinnamon",
        base_notes="Amber, Sandalwood, Tonka Bean, Cedar",
        scent="Marine aromatic woody amber",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Lattafa, Asad Zanzibar Limited Edition, Eau De Parfum, Men, 100ml, 3.4 oz, Marine Notes, Lavender, Tonka Bean, Amber",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Marine-spicy profile with aromatic freshness and warm amber woods.",
        ],
        similar_to=None,
        verified_note="Verified from the exact Jomashop barcode page, Fragrantica, and Parfumo. No exact official Lattafa USA page was found for this limited edition, so the saved profile follows the aligned retailer and fragrance-database sources only.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-mens-asad-zanzibar-edp-3-4-oz-fragrances-6290362347101.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-Zanzibar-Limited-Edition-122722.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/asad-zanzibar-limited-edition-zanzibar-limited-edition",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-mens-asad-zanzibar-edp-3-4-oz-fragrances-6290362347101.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.122722.jpg",
        ],
        official_discrepancy_note="Exact official Lattafa USA coverage was not found for this limited edition barcode, so the record is anchored to the exact Jomashop page plus Fragrantica and Parfumo alignment.",
    ),
    ProductSeed(
        product_id=62,
        barcode="6290360593135",
        brand="Lattafa",
        name="Lattafa Bade'e Al Oud Honor & Glory Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A creamy sweet-spicy unisex gourmand with pineapple and creme brulee up top, warm spiced benzoin through the heart, and a soft vanilla-wood base.",
        top_notes="Pineapple, Creme Brulee",
        mid_notes="Cinnamon, Turmeric, Black Pepper, Benzoin",
        base_notes="Vanilla, Sandalwood, Cashmeran, Moss",
        scent="Sweet creamy fruity gourmand",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Bade'e Al Oud Honor & Glory, Eau De Parfum, Unisex, 100ml, 3.4 oz, Pineapple, Creme Brulee, Vanilla, Cashmeran",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy pineapple gourmand profile with warm spiced vanilla depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Fragrantica, Parfumo, and Jomashop listing support. Source-backed wear guidance puts Honor & Glory in the sweeter cooler-weather, evening, and gourmand-friendly lane rather than hot-weather fresh use.",
        source_official_url="https://www.lattafa-usa.com/products/badee-al-oud-honor-and-glory",
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Bade-e-Al-Oud-Honor-Glory-84302.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/honor-glory",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.84302.jpg",
        ],
        official_discrepancy_note="Jomashop listing support exists for this barcode, but no stable direct product page was available by exact URL, so the note pyramid follows the official Lattafa USA page plus Fragrantica and Parfumo alignment.",
    ),
    ProductSeed(
        product_id=156,
        barcode="6290360599441",
        brand="Lattafa",
        name="Lattafa Bade'e Al Oud Noble Blush Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A soft rosy gourmand fragrance that opens with rose milk, develops a creamy almond-meringue heart, and settles into a smooth vanilla-sandalwood musk base.",
        top_notes="Rose Milk",
        mid_notes="Meringue, Almond",
        base_notes="Vanilla, Musk, Sandalwood",
        scent="Sweet powdery almond creamy",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Bade'e Al Oud Noble Blush, Eau De Parfum, Women, 100ml, 3.4 oz, Rose Milk, Almond, Meringue, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy rosy gourmand profile with almond and vanilla warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed guidance consistently places Noble Blush in the feminine soft-gourmand lane, especially for cooler weather, cozy wear, and sweet rosy everyday styling.",
        source_official_url="https://www.lattafa-usa.com/products/badee-al-oud-noble-blush",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-badee-al-oud-noble-blush-edp-spray-3-4-oz-fragrances-6290360599441.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Badee-Al-Oud-Noble-Blush-122812.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/noble-blush",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-ladies-badee-al-oud-noble-blush-edp-spray-3-4-oz-fragrances-6290360599441.jpg?width=800&height=800",
        ],
    ),
    ProductSeed(
        product_id=260,
        barcode="6290360598925",
        brand="Lattafa",
        name="Lattafa Dalal Eau de Parfum Spray 100ml (3.4 oz) Women's Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A feminine fruity-floral fragrance with apple and mandarin in the opening, a white-floral heart, and a smooth vanilla-musky finish.",
        top_notes="Golden Delicious Apple, Mandarin",
        mid_notes="Ylang-Ylang, Jasmine, Orange Flower",
        base_notes="Vanilla, Musk, Oakmoss",
        scent="Sweet floral fruity creamy",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Dalal, Eau De Parfum, Women, 100ml, 3.4 oz, Apple, Mandarin, Jasmine, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fruity-floral profile with soft vanilla-musky depth.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to an easy spring-friendly feminine daily scent with a mass-appeal floral-fruity profile rather than a heavy night fragrance.",
        source_official_url="https://www.lattafa-usa.com/products/dalal",
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-dalal-edp-spray-3-4-oz-fragrances-6290360598925.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Dalal-119588.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/dalal",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-ladies-dalal-edp-spray-3-4-oz-fragrances-6290360598925.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.119588.jpg",
        ],
    ),
    ProductSeed(
        product_id=129,
        barcode="6290360598857",
        brand="Lattafa",
        name="Lattafa Dynasty Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A refined fresh-spicy unisex fragrance with bergamot, ginger, and raspberry up top, a rooibos-suede heart, and a smooth amberwood cashmeran base.",
        top_notes="Bergamot, Ginger, Clary Sage, Nutmeg, Raspberry",
        mid_notes="Rooibos Tea, Suede",
        base_notes="Amberwood, Cedarwood, Cashmeran",
        scent="Fresh spicy woody aromatic",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Dynasty, Eau De Parfum, Unisex, 100ml, 3.4 oz, Bergamot, Rooibos Tea, Suede, Cashmeran",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh-spicy woody profile with tea and suede texture.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance points to a versatile polished daily driver that can work year-round, especially when you want something cleaner and smoother than sweeter Lattafa releases.",
        source_official_url="https://www.lattafa-usa.com/products/dynasty",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-dynasty-edp-spray-3-4-oz-fragrances-6290360598857.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Dynasty-112859.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/dynasty",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-dynasty-edp-spray-3-4-oz-fragrances-6290360598857.jpg?width=800&height=800",
        ],
    ),
    ProductSeed(
        product_id=42,
        barcode="6290362340638",
        brand="Lattafa",
        name="Lattafa Eclaire Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A cozy lactonic gourmand with caramel, milk, and sugar in the opening, honeyed white florals in the heart, and a creamy vanilla-praline musk base.",
        top_notes="Caramel, Milk, Sugar",
        mid_notes="Honey, White Flowers",
        base_notes="Vanilla, Praline, Musk",
        scent="Sweet gourmand creamy lactonic",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Eclaire, Eau De Parfum, Unisex, 100ml, 3.4 oz, Caramel, Milk, Honey, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Creamy caramel-vanilla gourmand profile with honeyed floral softness.",
        ],
        similar_to="Giardini di Toscana Bianco Latte",
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance consistently places Eclaire in the cozy gourmand lane, strongest for cooler weather, comfort wear, and sweet dessert-like styling.",
        source_official_url="https://www.lattafa-usa.com/products/eclaire",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-eclaire-edp-spray-3-4-oz-fragrances-6290362340638.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Eclaire-93628.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/eclaire",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-eclaire-edp-spray-3-4-oz-fragrances-6290362340638.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.93628.jpg",
        ],
        official_discrepancy_note="Fragrantica and Parfumo present Eclaire as women-leaning, while the current exact Lattafa USA page markets it as unisex; the saved record follows the official store positioning while keeping the shared sweet-gourmand profile.",
    ),
    ProductSeed(
        product_id=211,
        barcode="6290362349112",
        brand="Lattafa",
        name="Lattafa Eclaire Banoffi Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A playful banana gourmand with dulce de leche in the opening, whipped vanilla cream through the heart, and a sweet biscuit-praline musk base.",
        top_notes="Banana Cream, Dulce De Leche",
        mid_notes="Whipped Cream, Vanilla",
        base_notes="Praline, Biscuit, Musk",
        scent="Sweet gourmand creamy fruity",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Eclaire Banoffi, Eau De Parfum, Unisex, 100ml, 3.4 oz, Banana Cream, Dulce De Leche, Biscuit, Praline",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Banoffee-style gourmand profile with banana cream and biscuit-praline sweetness.",
        ],
        similar_to=None,
        verified_note="Verified from Lattafa USA, Jomashop, Fragrantica, and Parfumo. Source-backed wear guidance places Eclaire Banoffi firmly in the fun gourmand lane, best for casual wear, cozy settings, and sweet-fragrance fans rather than formal or heat-heavy use.",
        source_official_url="https://www.lattafa-usa.com/products/eclaire-banoffi",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-eclaire-banoffi-edp-spray-3-4-oz-fragrances-6290362349112.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Eclaire-Banoffi-113778.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/eclaire-banoffi",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-eclaire-banoffi-edp-spray-3-4-oz-fragrances-6290362349112.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.113778.jpg",
        ],
        official_discrepancy_note="Fragrantica and Parfumo describe the profile as women-and-men, while the current official Lattafa USA product page markets Eclaire Banoffi as unisex; the saved record follows the official store positioning.",
    ),
    ProductSeed(
        product_id=197,
        barcode="6290360591506",
        brand="Lattafa",
        name="Lattafa Emeer Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C.",
        description_intro="A citrusy-woody aromatic fragrance with lemon, bergamot, and juniper in the opening, tea and sandalwood in the heart, and a deep ambergris-cashmeran base.",
        top_notes="Lemon, Bergamot, Clary Sage, Juniper Berries",
        mid_notes="White Tea, Sandalwood, Cardamom, Olibanum",
        base_notes="Ambergris, Cedarwood, Cashmeran, Patchouli",
        scent="Citrusy woody aromatic spicy",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Lattafa, Emeer, Eau De Parfum, Unisex, 100ml, 3.4 oz, Lemon, White Tea, Ambergris, Cashmeran",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Citrus-woody aromatic profile with tea, ambergris, and cashmeran depth.",
        ],
        similar_to="Clive Christian Town & Country",
        verified_note="Verified from Lattafa USA, Jomashop listing support, Fragrantica, and Parfumo. The official page uses a broader family description than the fragrance databases, so the saved note pyramid follows the more detailed Fragrantica and Parfumo exact-match alignment.",
        source_official_url="https://www.lattafa-usa.com/products/emeer-1",
        source_jomashop_url="https://www.jomashop.com/lattafa-unisex-emeer-edp-3-4-oz-fragrances-6290360591506.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Emeer-89761.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/Lattafa/emeer",
        image_sources=[
            "https://cdn2.jomashop.com/media/catalog/product/cache/b3e31d40bbb1abcc90b26106659d5d3f/l/a/lattafa-unisex-emeer-edp-3-4-oz-fragrances-6290360591506.jpg?width=800&height=800",
            "https://fimgs.net/mdimg/perfume/375x500.89761.jpg",
        ],
        official_discrepancy_note="The current official Lattafa USA page gives a broader citrus-spice / leather-incense / oud-woody family description, while Fragrantica and Parfumo agree on a more detailed lemon-bergamot-tea-ambergris pyramid. The saved notes follow the detailed exact-match database alignment and preserve the discrepancy here.",
    ),
]


def update_product(seed: ProductSeed) -> dict[str, Any]:
    current = get_product(seed.product_id) or {}
    primary_image, gallery_json = build_gallery(seed, current)
    now = utc_now()
    updates = {
        "name": seed.name,
        "brand": seed.brand,
        "gender": seed.gender,
        "description": description_text(seed),
        "notes": seed.verified_note,
        "note_top": seed.top_notes,
        "note_mid": seed.mid_notes,
        "note_base": seed.base_notes,
        "size_oz": seed.size_oz,
        "size_ml": seed.size_ml,
        "volume_oz": seed.volume_oz,
        "volume_ml": seed.volume_ml,
        "media_url": primary_image,
        "image_gallery_urls": gallery_json,
        "notes_verified": 1,
        "notes_verified_at": now,
        "similar_to": seed.similar_to,
        "dupe_inspiration": seed.similar_to,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "tiktok_title": seed.name,
        "tiktok_item_name": seed.name,
        "tiktok_category_name": category_name_for_gender(seed.gender),
        "tiktok_brand": seed.brand,
        "tiktok_manufacturer": seed.manufacturer,
        "tiktok_feature": seed.feature,
        "tiktok_search_keywords": seed.keywords,
        "tiktok_scent": seed.scent,
        "tiktok_product_form": seed.product_form,
        "tiktok_fragrance_concentration": seed.product_form,
        "tiktok_volume": volume_text(seed),
        "tiktok_description": description_html(seed),
        "tiktok_highlights": "\n".join(seed.highlights),
        "tiktok_pack_type": "Single item" if seed.product_form != "Gift Set" else "Gift set",
        "tiktok_container_type": "Spray" if seed.product_form != "Gift Set" else "Multi-item set",
        "tiktok_age_group": "Adult",
        "tiktok_region_of_origin": "United Arab Emirates",
        "updated_at": now,
    }
    if seed.ingredients is not None:
        updates["ingredients"] = seed.ingredients
        updates["tiktok_ingredients"] = seed.ingredients
    if seed.package_weight_oz is not None:
        updates["tiktok_package_weight_oz"] = seed.package_weight_oz
    assignments = ", ".join(f"{column} = %s" for column in updates)
    params = list(updates.values()) + [seed.product_id]
    conn = _pg_connect()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"UPDATE {POSTGRES_SIDECAR_SCHEMA}.products SET {assignments} WHERE id = %s",
                    params,
                )
    finally:
        conn.close()
    return {
        "product_id": seed.product_id,
        "barcode": seed.barcode,
        "name": seed.name,
        "gallery_count": 0 if not gallery_json else len(json.loads(gallery_json)),
        "primary_image": primary_image,
        "source_official_url": seed.source_official_url,
        "source_jomashop_url": seed.source_jomashop_url,
        "source_fragrantica_url": seed.source_fragrantica_url,
        "source_parfumo_url": seed.source_parfumo_url,
        "discrepancy_note": seed.official_discrepancy_note,
    }


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
