#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.enrich_inventory_batch_20260427_third10 import (
    EXPORTS,
    ProductSeed,
    update_product,
)


REPORT_PATH = EXPORTS / "enrichment_batch_2026-04-27_twelfth10_report.json"


SEEDS: list[ProductSeed] = [
    ProductSeed(
        product_id=165,
        barcode="6291107459110",
        brand="Maison Alhambra",
        name="Maison Alhambra Avant Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A fresh men's eau de parfum with citrus and green notes on top, aromatic florals and spice in the heart, and a musky woody base.",
        top_notes="Bergamot, Lemon, Green Notes",
        mid_notes="Black Pepper, Jasmine, Lavender",
        base_notes="Vetiver, Patchouli, Musk",
        scent="Citrus fresh spicy aromatic",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Avant, Eau De Parfum, Men, 100ml, 3.4 oz, Bergamot, Lemon, Lavender, Musk",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Maison Alhambra.",
            "100 mL / 3.4 oz bottle size.",
            "Fresh citrus-aromatic profile with woody musky depth.",
        ],
        similar_to="Creed Aventus Cologne",
        verified_note="Verified from Fragrantica, Parfumo, and retailer support. The profile reads as a fresher aromatic take in the Aventus-inspired lane, with source-backed wear guidance favoring daytime, spring/summer, and casual office-friendly use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/maison-alhambra-mens-avant-edp-spray-3-4-oz-fragrances-6291107459110.html",
        source_fragrantica_url="https://www.fragrantica.com/p/92621",
        source_parfumo_url="https://www.parfumo.com/Perfumes/maison-alhambra/avant",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.92621.jpg",
        ],
        official_discrepancy_note="Fragrantica and Parfumo list different pyramids for Avant, so the saved notes follow the more consistent citrus-green aromatic structure rather than the fruitier Aventus-style alternative.",
    ),
    ProductSeed(
        product_id=161,
        barcode="6290360599205",
        brand="Maison Alhambra",
        name="Maison Alhambra Flaming Elixir Eau de Parfum Spray 80ml (2.7 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=2.7,
        size_ml=80,
        volume_oz=2.7,
        volume_ml=80,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A dark unisex eau de parfum with smoky cherry-spice character, soft floral nuance, and a warm ambered base.",
        top_notes="Saffron, Black Cherry",
        mid_notes="Jasmine, Rose",
        base_notes="Amber, Patchouli, Vanilla",
        scent="Fruity smoky sweet spicy",
        feature="eau de parfum spray; unisex; 80ml / 2.7 oz",
        keywords="Maison Alhambra, Flaming Elixir, Eau De Parfum, Unisex, 80ml, 2.7 oz, Black Cherry, Saffron, Amber, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra.",
            "80 mL / 2.7 oz bottle size.",
            "Smoky cherry profile with warm sweet amber depth.",
        ],
        similar_to="Tom Ford Cherry Smoke",
        verified_note="Verified from Parfumo, Fragrantica, and marketplace coverage. Community comparison consistently points toward Cherry Smoke, but public note pyramids vary, so the saved notes follow the most repeated dark-cherry smoky interpretation rather than the generic simplified listing.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Flaming-Elixir-129326.html",
        source_parfumo_url="https://www.parfumo.com/Parfums/maison-alhambra/flaming-elixir",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.129326.jpg",
        ],
        official_discrepancy_note="Fragrantica's public pyramid is unusually generic, while Parfumo review context and community cross-checks point to a smoky cherry-smoke style composition. The saved note set reflects that stronger consensus.",
    ),
    ProductSeed(
        product_id=269,
        barcode="6290362341130",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Bold Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A unisex eau de parfum in Maison Alhambra's Luxe line with a sweet-creamy character and limited trustworthy public note detail.",
        top_notes="Public note listings are limited",
        mid_notes="Public note listings are limited",
        base_notes="Public note listings are limited",
        scent="Sweet creamy luxe collection profile",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Bold, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Saved conservatively because public note details are still thin and inconsistent.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from barcode-linked retailer coverage and the Maison Alhambra Luxe family pattern. Public note structure is not yet reliable enough across sources, so this record preserves confirmed product facts without inventing a full pyramid.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="Luxe Bold currently has weak public fragrance-reference coverage, so the record was enriched conservatively around verified product identity, size, and classification only.",
    ),
    ProductSeed(
        product_id=164,
        barcode="6290362341147",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Chic Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A feminine eau de parfum in Maison Alhambra's Luxe line with a soft sweet-floral character and limited trustworthy public note detail.",
        top_notes="Public note listings are limited",
        mid_notes="Public note listings are limited",
        base_notes="Public note listings are limited",
        scent="Sweet floral luxe collection profile",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Chic, Eau De Parfum, Women, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Saved conservatively because public note details are still thin and inconsistent.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from barcode-linked marketplace coverage and Maison Alhambra Luxe collection references. Notes remain intentionally conservative until stronger source agreement appears.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="Luxe Chic still lacks stable fragrance-reference pages strong enough for a trustworthy full note pyramid, so the enrichment stays identity-focused.",
    ),
    ProductSeed(
        product_id=270,
        barcode="6290362341109",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Emerald Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A unisex eau de parfum in Maison Alhambra's Luxe line with a sweet-creamy profile and mixed public note information.",
        top_notes="Public note listings conflict across sources",
        mid_notes="Public note listings conflict across sources",
        base_notes="Public note listings conflict across sources",
        scent="Sweet creamy fruity luxe profile",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Emerald, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Identity enriched without forcing a disputed public note pyramid.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from barcode-linked retailer support and public Luxe collection coverage. Public note lists are inconsistent enough that the safer choice was to preserve identity, size, and classification without inventing a resolved pyramid.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="Public note listings for the Luxe sub-line have known cross-product contamination issues, so Luxe Emerald was saved conservatively.",
    ),
    ProductSeed(
        product_id=271,
        barcode="6290362341161",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Gold Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A unisex eau de parfum in Maison Alhambra's Luxe line with a sweet-creamy orientation and incomplete trustworthy public note coverage.",
        top_notes="Public note listings are limited",
        mid_notes="Public note listings are limited",
        base_notes="Public note listings are limited",
        scent="Sweet creamy luxe collection profile",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Gold, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Saved conservatively because public note detail is still too thin for a confident pyramid.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from barcode and collection references. Public note data is still too weak to support a clean pyramid, so this record stays fact-based without speculative note filling.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="Luxe Gold currently lacks strong enough public note sourcing for a reliable full pyramid.",
    ),
    ProductSeed(
        product_id=272,
        barcode="6290362341123",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Nightlife Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A unisex eau de parfum in Maison Alhambra's Luxe line with a richer sweet-creamy style and unresolved public note detail.",
        top_notes="Public note listings are limited",
        mid_notes="Public note listings are limited",
        base_notes="Public note listings are limited",
        scent="Sweet creamy luxe collection profile",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Nightlife, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Identity enriched conservatively while public note coverage matures.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from barcode-linked marketplace support and the Maison Alhambra Luxe family pattern. Public note pages are not strong enough yet to justify a detailed pyramid.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url=None,
        source_parfumo_url=None,
        image_sources=[],
        official_discrepancy_note="The Luxe Nightlife identity is confirmed, but the public note pyramid remains too weakly sourced for a confident fill.",
    ),
    ProductSeed(
        product_id=261,
        barcode="6294015149371",
        brand="Armaf",
        name="Armaf Odyssey Mandarin Sky Eau de Parfum Spray 100ml (3.4 oz) Men Perfume",
        gender="Men",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Sterling Perfumes Industries LLC",
        description_intro="A playful men's eau de parfum with mandarin and saffron on top, sweet caramel and tonka in the heart, and a woody ambroxan-vetiver base.",
        top_notes="Mandarin Orange, Orange, Saffron, Sage",
        mid_notes="Caramel, Tonka Bean, Marigold",
        base_notes="Ambroxan, Cedar, Vetiver",
        scent="Citrus sweet caramel woody",
        feature="eau de parfum spray; men; 100ml / 3.4 oz",
        keywords="Armaf, Odyssey Mandarin Sky, Eau De Parfum, Men, 100ml, 3.4 oz, Mandarin, Caramel, Tonka Bean, Ambroxan",
        highlights=[
            "Eau de parfum spray concentration.",
            "Men's fragrance from Armaf.",
            "100 mL / 3.4 oz bottle size.",
            "Bright mandarin opening with sweet caramel-tonka warmth.",
        ],
        similar_to="Jean Paul Gaultier Scandal Pour Homme",
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop support. Community comparison most often points toward the Scandal Pour Homme lane, and the source-backed wear fit is cooler evenings, clubbing, and sweet playful masculine use.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/armaf-mens-odyssey-mandarin-sky-edp-spray-3-4-oz-fragrances-6294015149371.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Armaf/Odyssey-Mandarin-Sky-83132.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Armaf/odyssey-mandarin-sky",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.83132.jpg",
        ],
    ),
    ProductSeed(
        product_id=174,
        barcode="6290362341093",
        brand="Maison Alhambra",
        name="Maison Alhambra Luxe Blanc Eau de Parfum Spray 100ml (3.4 oz) Unisex Perfume",
        gender="Unisex",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A unisex eau de parfum in Maison Alhambra's Luxe line with a soft sweet-creamy character and still-maturing public note coverage.",
        top_notes="Public note listings are limited",
        mid_notes="Public note listings are limited",
        base_notes="Public note listings are limited",
        scent="Sweet creamy luxe collection profile",
        feature="eau de parfum spray; unisex; 100ml / 3.4 oz",
        keywords="Maison Alhambra, Luxe Blanc, Eau De Parfum, Unisex, 100ml, 3.4 oz, Luxe Collection",
        highlights=[
            "Eau de parfum spray concentration.",
            "Unisex fragrance from Maison Alhambra's Luxe collection.",
            "100 mL / 3.4 oz bottle size.",
            "Saved with identity-first enrichment because public note detail is still weak.",
        ],
        similar_to=None,
        verified_note="Verified at the product identity level from Maison Alhambra Luxe collection coverage and retailer support. Public note information remains too inconsistent for a confident full pyramid, so the record stays conservative.",
        source_official_url=None,
        source_jomashop_url=None,
        source_fragrantica_url="https://www.fragrantica.com/perfume/Maison-Alhambra/Luxe-Blanc-114791.html",
        source_parfumo_url=None,
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.114791.jpg",
        ],
        official_discrepancy_note="Luxe Blanc public notes are still lightly sourced and may be cross-contaminated by other Luxe entries, so the record avoids a speculative pyramid.",
    ),
    ProductSeed(
        product_id=191,
        barcode="6291108735572",
        brand="Lattafa",
        name="Lattafa Mohra Silky Rose Eau de Parfum Spray 100ml (3.4 oz) Women Perfume",
        gender="Women",
        size_oz=3.4,
        size_ml=100,
        volume_oz=3.4,
        volume_ml=100,
        product_form="Eau De Parfum",
        manufacturer="Lattafa Perfumes Industries L.L.C",
        description_intro="A rosy women's eau de parfum with lychee and pink pepper sparkle, a musky rose heart, and a soft vanilla-patchouli base.",
        top_notes="Rose, Litchi, Pink Pepper",
        mid_notes="Rose, Musk, Lily-of-the-Valley",
        base_notes="Musk, Vanilla, Patchouli",
        scent="Rose musky fruity powdery",
        feature="eau de parfum spray; women; 100ml / 3.4 oz",
        keywords="Lattafa, Mohra Silky Rose, Eau De Parfum, Women, 100ml, 3.4 oz, Rose, Litchi, Musk, Vanilla",
        highlights=[
            "Eau de parfum spray concentration.",
            "Women's fragrance from Lattafa.",
            "100 mL / 3.4 oz bottle size.",
            "Soft rosy-musky profile with sweet vanilla patchouli warmth.",
        ],
        similar_to=None,
        verified_note="Verified from Fragrantica, Parfumo, and Jomashop support. Source-backed wear guidance points to an easy feminine rose scent that works for daily wear, spring, and soft romantic styling.",
        source_official_url=None,
        source_jomashop_url="https://www.jomashop.com/lattafa-ladies-mohra-silky-rose-edp-spray-3-4-oz-fragrances-6291108735572.html",
        source_fragrantica_url="https://www.fragrantica.com/perfume/Lattafa-Perfumes/Mohra-Silky-Rose-78383.html",
        source_parfumo_url="https://www.parfumo.com/Perfumes/Lattafa/mohra-silky-rose",
        image_sources=[
            "https://fimgs.net/mdimg/perfume/375x500.78383.jpg",
        ],
    ),
]


def main() -> int:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    results = [update_product(seed) for seed in SEEDS]
    REPORT_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=True), encoding="utf-8")
    print(json.dumps({"updated": len(results), "report": str(REPORT_PATH), "results": results}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
