{
    "name": "YNF TikTok Shop Connector",
    "version": "18.0.1.0.0",
    "category": "Sales/Sales",
    "summary": "TikTok Shop Partner API connector — OAuth, catalog, orders, fulfillment, returns",
    "depends": [
        "mail",
        "ynf_inventory",
        "ynf_tiktok_live",
        "sale_management",
        "sale_stock",
        "stock",
    ],
    "data": [
        "security/ynf_tiktok_shop_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/tiktok_shop_account_views.xml",
        "views/tiktok_product_map_views.xml",
        "views/tiktok_category_map_views.xml",
        "views/tiktok_api_log_views.xml",
        "views/tiktok_webhook_event_views.xml",
        "views/tiktok_return_views.xml",
        "views/res_config_settings_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
        "views/tiktok_connect_wizard_views.xml",
        "views/oauth_templates.xml",
        "views/menu.xml",
    ],
    "external_dependencies": {
        "python": ["cryptography"],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
