{
    "name": "YNF Deals — Luxury Fragrance Theme",
    "version": "18.0.4.2.0",
    "summary": "Mobile-first light luxury theme inspired by Lattafa USA for ynfdeals.com",
    "category": "Website/Theme",
    "author": "YNF Deals",
    "depends": ["website", "website_sale", "website_sale_stock", "portal"],
    "data": [
        "data/theme_data.xml",
        "views/layout_templates.xml",
        "views/homepage_templates.xml",
        "views/shop_templates.xml",
        "views/product_templates.xml",
        "views/lattafa_sections.xml",
        "views/portal_templates.xml",
        "views/live_page.xml",
        "views/homepage_design_sections.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "ynf_website_theme/static/src/scss/theme_variables.scss",
            "ynf_website_theme/static/src/scss/frontend.scss",
            "ynf_website_theme/static/src/scss/header.scss",
            "ynf_website_theme/static/src/scss/homepage.scss",
            "ynf_website_theme/static/src/scss/shop.scss",
            "ynf_website_theme/static/src/scss/product.scss",
            "ynf_website_theme/static/src/scss/checkout.scss",
            "ynf_website_theme/static/src/scss/mobile.scss",
            "ynf_website_theme/static/src/scss/editor_homepage_fix.scss",
            "ynf_website_theme/static/src/scss/light_homepage.scss",
            "ynf_website_theme/static/src/scss/lattafa_sections.scss",
            "ynf_website_theme/static/src/scss/mobile_redesign.scss",
            "ynf_website_theme/static/src/scss/amazon_mobile.scss",
            "ynf_website_theme/static/src/scss/notes_pyramid.scss",
            "ynf_website_theme/static/src/scss/homepage_design_sections.scss",
            "ynf_website_theme/static/src/js/theme.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
    "post_init_hook": "_ynf_post_init",
}
